"use strict";
/* ================= フレーズデータ(v5.0.0) =================
   「日本語は出てくるが英語が出てこない」の解消用: 談話機能別のstem(文の骨組み)と
   トピック別コロケーションの2種類。守備範囲の優先度は 英検1級二次 > 仕事会議・雑談 > TOEIC/IELTS。
   フィールド:
     c : カテゴリ(PHR_CATS)
     ty: "s"=文の骨組み(stem) / "c"=コロケーション(平易な語の結びつき=産出語彙の受け皿)
     k : 核になる語・連語(結果表示の🔑と辞書リンクに使う)
     ja: 「言いたい意図」(直訳ではなく、実際の発話と同じ 意図→英語 の検索経路を作る)
     ch: 並べ替え用のチャンク分割。en は ch.join(" ") で導出する
   ★重要: 公開後に ch を変えないこと(en=SRS記録のキー。words.js の en と同じ不変制約)。
   誤りを見つけたら新項目を足し、旧項目は削除する(記録キーの付け替えはしない) */
const PHR_CATS={
  op:"意見・立場", ag:"賛成・反論", rs:"理由・例示", str:"話の構成",
  num:"数値・傾向", hyp:"仮定・推測", fix:"言い換え・つなぎ",
  env:"環境", edu:"教育", tec:"テクノロジー", med:"医療・高齢化",
  eco:"経済・格差", pol:"政治・国際", mda:"メディア・社会",
  biz:"仕事・会議", sm:"雑談",
  vp:"動詞の型", ims:"無生物主語", // v5.4.0: make/help/force頼みからの卒業(pt=型の一般形つき)
};
const PHRASES=[
/* ---- op: 意見・立場(stem) ---- */
{c:"op",ty:"s",k:"see",ja:"私の見方では、…",ch:["The way","I see it,","…"]},
{c:"op",ty:"s",k:"inclined",ja:"どちらかと言えば〜だと思う",ch:["I'm inclined","to think","that …"]},
{c:"op",ty:"s",k:"point of view",ja:"私の観点から言うと、…",ch:["From my","point of view,","…"]},
{c:"op",ty:"s",k:"say",ja:"(軽く)〜だと思うな",ch:["I'd say","that …"]},
{c:"op",ty:"s",k:"ask",ja:"私に言わせれば、…",ch:["If you","ask me,","…"]},
{c:"op",ty:"s",k:"convinced",ja:"〜だと確信している",ch:["I'm convinced","that …"]},
{c:"op",ty:"s",k:"concerned",ja:"私に関する限り、…",ch:["As far as","I'm concerned,","…"]},
{c:"op",ty:"s",k:"gut",ja:"直感では〜だ",ch:["My gut feeling","is that …"]},
{c:"op",ty:"s",k:"mixed",ja:"これには複雑な心境だ",ch:["I have","mixed feelings","about this."]},
{c:"op",ty:"s",k:"entirely",ja:"確信はないけれど、…",ch:["I'm not","entirely sure,","but …"]},
{c:"op",ty:"s",k:"seem",ja:"〜のように思える",ch:["It seems","to me","that …"]},
{c:"op",ty:"s",k:"rather",ja:"個人的にはむしろ〜したい",ch:["Personally speaking,","I'd rather","…"]},
{c:"op",ty:"s",k:"strongly",ja:"〜だと強く思う",ch:["I feel","strongly","that …"]},
{c:"op",ty:"s",k:"honest",ja:"正直に言うと、…",ch:["To be","honest with you,","…"]},
{c:"op",ty:"s",k:"used to",ja:"昔はそう思っていたが、今は…",ch:["I used to","think so,","but now …"]},
{c:"op",ty:"s",k:"balance",ja:"総合的に見て賛成だ",ch:["On balance,","I'm in favor","of it."]},
/* ---- ag: 賛成・反論・譲歩(stem) ---- */
{c:"ag",ty:"s",k:"fair point",ja:"もっともな指摘だが、自分は違う見方だ",ch:["That's a fair point,","but","I see it differently."]},
{c:"ag",ty:"s",k:"agree",ja:"全面的に同意する",ch:["I couldn't","agree more."]},
{c:"ag",ty:"s",k:"up to a point",ja:"ある程度までは同意する",ch:["I agree with you","up to a point."]},
{c:"ag",ty:"s",k:"coming from",ja:"言いたいことは分かるが、…",ch:["I see where","you're coming from,","but …"]},
{c:"ag",ty:"s",k:"in practice",ja:"理論上はそうだが、実際には…",ch:["That's true in theory,","but in practice","…"]},
{c:"ag",ty:"s",k:"disagree",ja:"残念ながら反対せざるを得ない",ch:["I'm afraid","I have to","disagree."]},
{c:"ag",ty:"s",k:"point",ja:"それは一理あるね",ch:["You have","a point there."]},
{c:"ag",ty:"s",k:"misses the point",ja:"そうかもしれないが、論点がずれている",ch:["That may be true,","but it misses","the point."]},
{c:"ag",ty:"s",k:"push back",ja:"その考えには異を唱えたい",ch:["I'd like to","push back","on that idea."]},
{c:"ag",ty:"s",k:"agree to disagree",ja:"見解の相違ということにしよう",ch:["Let's agree","to disagree."]},
{c:"ag",ty:"s",k:"depend",ja:"それは見方によるね",ch:["It depends on","how you look at it."]},
{c:"ag",ty:"s",k:"reservations",ja:"部分的には同意だが、留保もある",ch:["I partly agree,","but I have","some reservations."]},
{c:"ag",ty:"s",k:"exactly",ja:"まさにそう思っていた",ch:["That's exactly","what I was thinking."]},
{c:"ag",ty:"s",k:"take your point",ja:"コストについての指摘はもっともだ",ch:["I take your point","about the cost."]},
{c:"ag",ty:"s",k:"granted",ja:"確かに欠点はあるが、…",ch:["Granted,","it has some drawbacks,","but …"]},
{c:"ag",ty:"s",k:"having said",ja:"とはいえ、…",ch:["Having said that,","…"]},
{c:"ag",ty:"s",k:"other hand",ja:"一方で、…",ch:["On the","other hand,","…"]},
{c:"ag",ty:"s",k:"necessarily",ja:"必ずしもそうとは限らない",ch:["That's not","necessarily","the case."]},
{c:"ag",ty:"s",k:"go so far",ja:"そこまでは言わないな",ch:["I wouldn't go","so far as","to say that."]},
{c:"ag",ty:"s",k:"both sides",ja:"どちらの側にも言い分がある",ch:["There's something","to be said","for both sides."]},
/* ---- rs: 理由・例示(stem) ---- */
{c:"rs",ty:"s",k:"main reason",ja:"主な理由は〜だ",ch:["The main reason","is that …"]},
{c:"rs",ty:"s",k:"case in point",ja:"その好例が〜だ",ch:["A case in point","is …"]},
{c:"rs",ty:"s",k:"for example",ja:"例えば日本を見てほしい",ch:["Take Japan,","for example."]},
{c:"rs",ty:"s",k:"partly",ja:"これは一部には〜が原因だ",ch:["This is","partly because","…"]},
{c:"rs",ty:"s",k:"precisely",ja:"まさにそれが理由で〜なのだ",ch:["That's precisely","why …"]},
{c:"rs",ty:"s",k:"concrete",ja:"具体例を挙げると、…",ch:["To give you","a concrete example,","…"]},
{c:"rs",ty:"s",k:"evidence",ja:"証拠は〜を示している",ch:["The evidence","suggests","that …"]},
{c:"rs",ty:"s",k:"keep in mind",ja:"念頭に置くべきことが1つある",ch:["One thing","to keep in mind","is that …"]},
{c:"rs",ty:"s",k:"backed up",ja:"これは研究にも裏付けられている",ch:["This is","backed up","by research."]},
{c:"rs",ty:"s",k:"judging",ja:"自分の経験から判断すると、…",ch:["Judging from","my own experience,","…"]},
{c:"rs",ty:"s",k:"mean",ja:"それはつまりこういう意味だ",ch:["What I mean","by that","is …"]},
{c:"rs",ty:"s",k:"boils down to",ja:"要は優先順位の問題に尽きる",ch:["It boils down to","a matter of","priorities."]},
{c:"rs",ty:"s",k:"reasons",ja:"これには主な理由が2つある",ch:["There are","two main reasons","for this."]},
{c:"rs",ty:"s",k:"factor",ja:"考慮すべきもう1つの要因は…",ch:["Another factor","to consider","is …"]},
{c:"rs",ty:"s",k:"often the case",ja:"日本ではよくあることだが、…",ch:["As is often the case","with Japan,","…"]},
{c:"rs",ty:"s",k:"experience",ja:"経験から言うと、…",ch:["Speaking from","experience,","…"]},
{c:"rs",ty:"s",k:"explain",ja:"これが〜の理由の説明になる",ch:["This explains","why …"]},
{c:"rs",ty:"s",k:"instance",ja:"例えばリモートワークの事例を考えてほしい",ch:["For instance,","consider the case of","remote work."]},
/* ---- str: 話の構成(stem・2分スピーチ) ---- */
{c:"str",ty:"s",k:"talk about",ja:"今日は〜について話したい",ch:["Today,","I'd like to","talk about …"]},
{c:"str",ty:"s",k:"points",ja:"述べたいポイントは3つある",ch:["There are three points","I'd like to make."]},
{c:"str",ty:"s",k:"define",ja:"まず問題を定義させてほしい",ch:["First of all,","let me define","the problem."]},
{c:"str",ty:"s",k:"start with",ja:"いちばん重要な点から始めよう",ch:["Let me start with","the most important point."]},
{c:"str",ty:"s",k:"moving on",ja:"2つ目のポイントに移ると、…",ch:["Moving on to","my second point,","…"]},
{c:"str",ty:"s",k:"brings me",ja:"ここから次のポイントにつながる",ch:["This brings me","to my next point."]},
{c:"str",ty:"s",k:"sum up",ja:"まとめると、…",ch:["To sum up,","…"]},
{c:"str",ty:"s",k:"outweigh",ja:"結論として、利点が欠点を上回ると思う",ch:["In conclusion,","I believe the benefits","outweigh the drawbacks."]},
{c:"str",ty:"s",k:"wrap up",ja:"最後に〜と言って締めくくりたい",ch:["Let me wrap up","by saying","that …"]},
{c:"str",ty:"s",k:"mentioned",ja:"先ほど述べたように、…",ch:["As I mentioned","earlier,","…"]},
{c:"str",ty:"s",k:"going back",ja:"さっき言ったことに戻ると、…",ch:["Going back to","what I said before,","…"]},
{c:"str",ty:"s",k:"trying to make",ja:"私が言いたいポイントは〜だ",ch:["The point","I'm trying to make","is that …"]},
{c:"str",ty:"s",k:"background",ja:"まず背景を説明させてほしい",ch:["Let me give you","some background","first."]},
{c:"str",ty:"s",k:"covers",ja:"言いたいことは以上です",ch:["That covers everything","I wanted to say."]},
/* ---- num: 数値・傾向・一般論(stem・グラフ描写兼用) ---- */
{c:"num",ty:"s",k:"third",ja:"人口のおよそ3分の1が…",ch:["Roughly a third","of the population","…"]},
{c:"num",ty:"s",k:"double",ja:"その数はこの10年で2倍になった",ch:["The number has doubled","over the past decade."]},
{c:"num",ty:"s",k:"decline",ja:"それはじわじわ減り続けている",ch:["It has been","on a steady decline."]},
{c:"num",ty:"s",k:"peak",ja:"数値は2020年に頂点を打ち、その後急落した",ch:["The figure peaked in 2020","and then dropped sharply."]},
{c:"num",ty:"s",k:"gradual",ja:"〜は緩やかに増えてきている",ch:["There has been","a gradual increase","in …"]},
{c:"num",ty:"s",k:"accounts for",ja:"それは全体の約2割を占める",ch:["It accounts for","about 20 percent","of the total."]},
{c:"num",ty:"s",k:"widen",ja:"その差は年々広がっている",ch:["The gap is widening","year by year."]},
{c:"num",ty:"s",k:"flat",ja:"それはほぼ横ばいだった",ch:["It remained","more or less flat."]},
{c:"num",ty:"s",k:"nine out of ten",ja:"10人中9人は〜に同意するだろう",ch:["Nine out of ten people","would agree","that …"]},
{c:"num",ty:"s",k:"argued",ja:"〜だとよく主張される",ch:["It is often","argued that …"]},
{c:"num",ty:"s",k:"widely",ja:"〜だと広く信じられている",ch:["It is widely","believed that …"]},
{c:"num",ty:"s",k:"tendency",ja:"〜する傾向が強まっている",ch:["There is a","growing tendency","to …"]},
{c:"num",ty:"s",k:"statistics",ja:"統計は〜を示している",ch:["Statistics show","that …"]},
{c:"num",ty:"s",k:"trend",ja:"この傾向は続きそうだ",ch:["The trend is likely","to continue."]},
{c:"num",ty:"s",k:"margin",ja:"それは大差で勝った",ch:["It won","by a wide margin."]},
{c:"num",ty:"s",k:"twice as",ja:"これは世界平均の2倍の高さだ",ch:["This is twice as high","as the global average."]},
{c:"num",ty:"s",k:"level off",ja:"その率は頭打ちになる見込みだ",ch:["The rate is expected","to level off."]},
{c:"num",ty:"s",k:"compared",ja:"20年前と比べると、…",ch:["Compared to","twenty years ago,","…"]},
/* ---- hyp: 仮定・推測(stem) ---- */
{c:"hyp",ty:"s",k:"chances are",ja:"おそらく悪化するだろう",ch:["Chances are","it will get worse."]},
{c:"hyp",ty:"s",k:"suppose",ja:"仮に全面禁止したとしよう",ch:["Suppose we were to","ban it altogether."]},
{c:"hyp",ty:"s",k:"were the case",ja:"もしそうだとしたら、…",ch:["If that were","the case,","…"]},
{c:"hyp",ty:"s",k:"either way",ja:"どちらに転ぶか分からない",ch:["It could go","either way."]},
{c:"hyp",ty:"s",k:"worst-case",ja:"最悪のシナリオでは、…",ch:["In the","worst-case scenario,","…"]},
{c:"hyp",ty:"s",k:"for sure",ja:"断言はできないが、…",ch:["It's hard to say","for sure,","but …"]},
{c:"hyp",ty:"s",k:"position",ja:"あなたの立場なら私は〜するだろう",ch:["If I were in your position,","I would …"]},
{c:"hyp",ty:"s",k:"circumstances",ja:"それは状況次第だろう",ch:["That would depend","on the circumstances."]},
{c:"hyp",ty:"s",k:"hypothetically",ja:"仮の話として、…",ch:["Hypothetically","speaking,","…"]},
{c:"hyp",ty:"s",k:"matter of time",ja:"〜するのは時間の問題だ",ch:["It's only a matter of time","before …"]},
{c:"hyp",ty:"s",k:"surprised",ja:"そうなっても驚かないね",ch:["I wouldn't be surprised","if that happened."]},
{c:"hyp",ty:"s",k:"assume",ja:"ひとまずうまくいくと仮定しよう",ch:["Let's assume","for the moment","that it works."]},
/* ---- fix: 言い換え・つなぎ・時間稼ぎ(stem・二次Q&Aの生命線) ---- */
{c:"fix",ty:"s",k:"good question",ja:"(時間を稼ぐ)いい質問ですね",ch:["That's a","good question."]},
{c:"fix",ty:"s",k:"think",ja:"少し考えさせてください",ch:["Let me think about that","for a second."]},
{c:"fix",ty:"s",k:"put it",ja:"何と言えばいいかな…",ch:["How should","I put it?"]},
{c:"fix",ty:"s",k:"another way",ja:"別の言い方をしてみます",ch:["Let me put it","another way."]},
{c:"fix",ty:"s",k:"trying to say",ja:"私が言おうとしているのは…",ch:["What I'm","trying to say","is …"]},
{c:"fix",ty:"s",k:"in other words",ja:"言い換えると、…",ch:["In other","words,","…"]},
{c:"fix",ty:"s",k:"tip of my tongue",ja:"喉まで出かかっているんだけど",ch:["It's on the tip","of my tongue."]},
{c:"fix",ty:"s",k:"rephrase",ja:"すみません、言い直します",ch:["Sorry,","let me rephrase that."]},
{c:"fix",ty:"s",k:"again",ja:"もう一度言ってもらえますか",ch:["Could you say that","again, please?"]},
{c:"fix",ty:"s",k:"mean by",ja:"それは正確にはどういう意味ですか",ch:["What do you mean","by that","exactly?"]},
{c:"fix",ty:"s",k:"understood",ja:"正しく理解できていれば、…ということですね",ch:["If I understood you","correctly,","…"]},
{c:"fix",ty:"s",k:"not quite",ja:"言いたかったのはそういうことではなくて",ch:["That's not quite","what I meant."]},
{c:"fix",ty:"s",k:"train of thought",ja:"何を言おうとしてたか忘れてしまった",ch:["I lost my","train of thought."]},
{c:"fix",ty:"s",k:"where was I",ja:"どこまで話しましたっけ?",ch:["Where","was I?"]},
{c:"fix",ty:"s",k:"simply",ja:"簡単に言えば、…",ch:["To put it","simply,","…"]},
{c:"fix",ty:"s",k:"makes sense",ja:"…って、伝わりますかね",ch:["…,","if that","makes sense."]},
{c:"fix",ty:"s",k:"something like",ja:"単語が出てこないけど、〜みたいなもので",ch:["I can't think of the word,","but it's","something like …"]},
{c:"fix",ty:"s",k:"top of my head",ja:"ぱっと思いつきでは50くらいかな",ch:["Off the top of my head,","I'd say","around fifty."]},
/* ---- env: 環境 ---- */
{c:"env",ty:"c",k:"renewable energy",ja:"再生可能エネルギーに切り替えるべきだ",ch:["We should switch to","renewable energy sources."]},
{c:"env",ty:"c",k:"poses a serious threat",ja:"地球温暖化は人類への深刻な脅威だ",ch:["Global warming poses","a serious threat","to humanity."]},
{c:"env",ty:"c",k:"extreme weather",ja:"異常気象がますます頻発している",ch:["Extreme weather events","are becoming","more frequent."]},
{c:"env",ty:"c",k:"plastic waste",ja:"プラスチックごみが海を汚染している",ch:["Plastic waste","is polluting","the oceans."]},
{c:"env",ty:"c",k:"carbon footprint",ja:"私たちは炭素排出量を減らす必要がある",ch:["We need to reduce","our carbon footprint."]},
{c:"env",ty:"c",k:"impose a carbon tax",ja:"政府は炭素税を課すべきだ",ch:["The government should","impose a carbon tax."]},
{c:"env",ty:"c",k:"endangered species",ja:"絶滅危惧種の保護は世界全体の責任だ",ch:["Protecting endangered species","is a global responsibility."]},
{c:"env",ty:"c",k:"habitat",ja:"森林破壊が野生生物のすみかを壊している",ch:["Deforestation is destroying","wildlife habitats."]},
{c:"env",ty:"c",k:"make a difference",ja:"リサイクルのような日々の努力にも意味がある",ch:["Everyday efforts like recycling","can make a difference."]},
{c:"env",ty:"c",k:"controversial",ja:"原子力発電は今も賛否が分かれる選択肢だ",ch:["Nuclear power remains","a controversial option."]},
{c:"env",ty:"c",k:"held accountable",ja:"企業は汚染の責任を問われるべきだ",ch:["Companies should be","held accountable","for pollution."]},
{c:"env",ty:"c",k:"sustainable",ja:"持続可能な開発は将来世代のためになる",ch:["Sustainable development","benefits","future generations."]},
{c:"env",ty:"c",k:"gaining popularity",ja:"電気自動車は世界中で人気を集めている",ch:["Electric vehicles","are gaining popularity","worldwide."]},
{c:"env",ty:"c",k:"hits",ja:"気候変動は発展途上国を最も直撃する",ch:["Climate change hits","developing countries","hardest."]},
{c:"env",ty:"c",k:"running out of",ja:"天然資源は枯渇しつつある",ch:["We are running out of","natural resources."]},
{c:"env",ty:"c",k:"clash",ja:"環境規制は経済成長としばしば衝突する",ch:["Environmental regulations","often clash with","economic growth."]},
{c:"env",ty:"c",k:"individual action",ja:"個人の行動だけでは気候変動は解決できない",ch:["Individual action alone","cannot solve","climate change."]},
{c:"env",ty:"c",k:"sea levels",ja:"海面上昇が沿岸都市を脅かしている",ch:["Rising sea levels","threaten","coastal cities."]},
/* ---- edu: 教育 ---- */
{c:"edu",ty:"c",k:"plays a key role in",ja:"教育は貧困削減に重要な役割を果たす",ch:["Education plays a key role","in reducing poverty."]},
{c:"edu",ty:"c",k:"think critically",ja:"子どもは批判的に考えるよう促されるべきだ",ch:["Children should be encouraged","to think critically."]},
{c:"edu",ty:"c",k:"emphasis",ja:"今の制度は試験を重視しすぎている",ch:["The current system puts","too much emphasis","on exams."]},
{c:"edu",ty:"c",k:"accessible",ja:"オンライン学習は教育をより身近にした",ch:["Online learning has made","education more accessible."]},
{c:"edu",ty:"c",k:"underpaid",ja:"教師は働きすぎな上に薄給だ",ch:["Teachers are overworked","and underpaid."]},
{c:"edu",ty:"c",k:"pays off",ja:"幼児教育は長期的に見て報われる",ch:["Early childhood education","pays off","in the long run."]},
{c:"edu",ty:"c",k:"practical skills",ja:"生徒は学校で実用的なスキルを学ぶべきだ",ch:["Students should learn","practical skills","at school."]},
{c:"edu",ty:"c",k:"focuses too much on",ja:"日本の英語教育は文法に偏りすぎている",ch:["English education in Japan","focuses too much","on grammar."]},
{c:"edu",ty:"c",k:"lifelong learning",ja:"生涯学習の重要性が増している",ch:["Lifelong learning is becoming","increasingly important."]},
{c:"edu",ty:"c",k:"financial support",ja:"低所得の学生には経済的支援を与えるべきだ",ch:["Financial support should be given","to low-income students."]},
{c:"edu",ty:"c",k:"do more harm",ja:"教室のスマホは益より害が大きい",ch:["Smartphones in the classroom","do more harm","than good."]},
{c:"edu",ty:"c",k:"not for everyone",ja:"大学教育が万人向けとは限らない",ch:["University education","is not for everyone."]},
{c:"edu",ty:"c",k:"motivate",ja:"競争はやる気を出させる生徒もいればくじく生徒もいる",ch:["Competition motivates some students","but discourages others."]},
{c:"edu",ty:"c",k:"put too much pressure on",ja:"親は子どもに過度なプレッシャーをかけがちだ",ch:["Parents tend to put","too much pressure","on children."]},
{c:"edu",ty:"c",k:"broaden",ja:"留学は視野を広げてくれる",ch:["Studying abroad","broadens your horizons."]},
{c:"edu",ty:"c",k:"birthrate",ja:"少子化で学校が閉校に追い込まれている",ch:["The declining birthrate","is forcing schools","to close."]},
{c:"edu",ty:"c",k:"moral education",ja:"道徳は教科書だけでは教えられない",ch:["Moral education cannot be taught","through textbooks alone."]},
{c:"edu",ty:"c",k:"human right",ja:"教育へのアクセスは基本的人権だ",ch:["Access to education","is a basic human right."]},
/* ---- tec: テクノロジー ---- */
{c:"tec",ty:"c",k:"transform",ja:"AIは働き方を一変させるだろう",ch:["AI will transform","the way we work."]},
{c:"tec",ty:"c",k:"take over",ja:"自動化が定型的な仕事を奪うかもしれない",ch:["Automation may take over","routine jobs."]},
{c:"tec",ty:"c",k:"rely too heavily on",ja:"私たちはスマホに頼りすぎている",ch:["We rely too heavily","on smartphones."]},
{c:"tec",ty:"c",k:"personal data",ja:"個人データは細心の注意をもって扱うべきだ",ch:["Personal data should be handled","with great care."]},
{c:"tec",ty:"c",k:"misinformation",ja:"SNSは誤情報を恐ろしい速さで拡散する",ch:["Social media spreads misinformation","at alarming speed."]},
{c:"tec",ty:"c",k:"double-edged",ja:"テクノロジーは諸刃の剣だ",ch:["Technology is","a double-edged sword."]},
{c:"tec",ty:"c",k:"the norm",ja:"キャッシュレス決済が当たり前になりつつある",ch:["Cashless payments","are becoming","the norm."]},
{c:"tec",ty:"c",k:"growing concern",ja:"サイバーセキュリティは企業の懸念事項として拡大している",ch:["Cybersecurity is a growing concern","for companies."]},
{c:"tec",ty:"c",k:"ethical",ja:"新技術はしばしば倫理的な問いを投げかける",ch:["New technologies often raise","ethical questions."]},
{c:"tec",ty:"c",k:"digital divide",ja:"デジタル格差が高齢者を置き去りにしている",ch:["The digital divide","leaves elderly people","behind."]},
{c:"tec",ty:"c",k:"widespread",ja:"リモートワークはパンデミック以降広く普及した",ch:["Remote work has become widespread","since the pandemic."]},
{c:"tec",ty:"c",k:"drives economic growth",ja:"イノベーションが経済成長を牽引する",ch:["Innovation drives","economic growth."]},
{c:"tec",ty:"c",k:"self-driving",ja:"自動運転車は交通事故を減らせるかもしれない",ch:["Self-driving cars could reduce","traffic accidents."]},
{c:"tec",ty:"c",k:"safely",ja:"子どもには安全なネットの使い方を教えるべきだ",ch:["We should teach children","how to use the internet","safely."]},
{c:"tec",ty:"c",k:"replace",ja:"対面の会話が文字のやり取りに置き換わりつつある",ch:["Face-to-face communication","is being replaced","by texting."]},
{c:"tec",ty:"c",k:"convenient",ja:"テクノロジーは生活をかつてなく便利にした",ch:["Technology has made our lives","more convenient than ever."]},
{c:"tec",ty:"c",k:"emerge",ja:"消える仕事もあるが、新しい仕事も生まれる",ch:["Some jobs will disappear,","but new ones","will emerge."]},
{c:"tec",ty:"c",k:"striking a balance between",ja:"利便性とプライバシーの両立は難しい",ch:["Striking a balance between","convenience and privacy","is difficult."]},
/* ---- med: 医療・高齢化 ---- */
{c:"med",ty:"c",k:"aging population",ja:"日本は急速に高齢化が進んでいる",ch:["Japan has a rapidly","aging population."]},
{c:"med",ty:"c",k:"pension",ja:"少子化が年金制度を脅かしている",ch:["The declining birthrate","threatens the pension system."]},
{c:"med",ty:"c",k:"burden",ja:"医療費が政府に重い負担をかけている",ch:["Healthcare costs are placing","a heavy burden","on the government."]},
{c:"med",ty:"c",k:"preventive",ja:"予防医療は治療より費用対効果が高い",ch:["Preventive care is more","cost-effective than treatment."]},
{c:"med",ty:"c",k:"shortage",ja:"介護職員が深刻に不足している",ch:["There is a serious shortage","of nursing care workers."]},
{c:"med",ty:"c",k:"living longer",ja:"人々はかつてないほど長生きしている",ch:["People are living longer","than ever before."]},
{c:"med",ty:"c",k:"overlooked",ja:"日本ではメンタルヘルスが軽視されがちだ",ch:["Mental health issues are often","overlooked in Japan."]},
{c:"med",ty:"c",k:"reduces the risk of",ja:"定期的な運動は生活習慣病のリスクを下げる",ch:["Regular exercise reduces the risk","of lifestyle diseases."]},
{c:"med",ty:"c",k:"retirement age",ja:"定年は段階的に引き上げるべきだ",ch:["The retirement age should be","raised gradually."]},
{c:"med",ty:"c",k:"isolation",ja:"高齢者は社会的孤立に苦しみがちだ",ch:["Elderly people often suffer","from social isolation."]},
{c:"med",ty:"c",k:"work-life balance",ja:"健康にはワークライフバランスが不可欠だ",ch:["Work-life balance is essential","for good health."]},
{c:"med",ty:"c",k:"life expectancy",ja:"医学の進歩が平均寿命を延ばした",ch:["Medical advances have extended","our life expectancy."]},
{c:"med",ty:"c",k:"caring for",ja:"年老いた親の介護は大きな関心事になっている",ch:["Caring for aging parents","is a growing concern."]},
{c:"med",ty:"c",k:"universal healthcare",ja:"国民皆保険は日本の強みの1つだ",ch:["Universal healthcare is one of","Japan's strengths."]},
/* ---- eco: 経済・格差 ---- */
{c:"eco",ty:"c",k:"gap",ja:"貧富の差が広がっている",ch:["The gap between rich and poor","is widening."]},
{c:"eco",ty:"c",k:"income inequality",ja:"所得格差は社会の安定を損なう",ch:["Income inequality undermines","social stability."]},
{c:"eco",ty:"c",k:"minimum wage",ja:"最低賃金は引き上げるべきだ",ch:["The minimum wage","should be raised."]},
{c:"eco",ty:"c",k:"struggling to survive",ja:"中小企業は生き残りに苦しんでいる",ch:["Small businesses are struggling","to survive."]},
{c:"eco",ty:"c",k:"cost of living",ja:"生活費が上がり続けている",ch:["The cost of living","keeps going up."]},
{c:"eco",ty:"c",k:"job security",ja:"高給より雇用の安定の方が大事だ",ch:["Job security matters more","than a high salary."]},
{c:"eco",ty:"c",k:"recovery",ja:"経済は回復の兆しを見せている",ch:["The economy is showing","signs of recovery."]},
{c:"eco",ty:"c",k:"winners and losers",ja:"グローバル化は勝者と敗者を生んだ",ch:["Globalization has created","winners and losers."]},
{c:"eco",ty:"c",k:"unpopular",ja:"増税は常に不人気だが、時に必要だ",ch:["Raising taxes is always unpopular","but sometimes necessary."]},
{c:"eco",ty:"c",k:"afford",ja:"多くの若者は家を買う余裕がない",ch:["Many young people cannot afford","to buy a house."]},
{c:"eco",ty:"c",k:"consumer spending",ja:"個人消費が経済成長を支えている",ch:["Consumer spending drives","economic growth."]},
{c:"eco",ty:"c",k:"long-term",ja:"企業は短期の利益より長期の成長を優先すべきだ",ch:["Companies should prioritize long-term growth","over short-term profit."]},
{c:"eco",ty:"c",k:"invest",ja:"政府はインフラにもっと投資すべきだ",ch:["The government should invest more","in infrastructure."]},
{c:"eco",ty:"c",k:"eating into",ja:"インフレが家計を圧迫している",ch:["Inflation is eating into","household budgets."]},
{c:"eco",ty:"c",k:"labor shortage",ja:"人手不足は日本の差し迫った課題だ",ch:["The labor shortage is","a pressing issue","in Japan."]},
{c:"eco",ty:"c",k:"at the expense",ja:"経済成長は環境を犠牲にしてはならない",ch:["Economic growth should not come","at the expense of","the environment."]},
{c:"eco",ty:"c",k:"passed down",ja:"貧困は世代から世代へ受け継がれがちだ",ch:["Poverty is often passed down","from generation to generation."]},
{c:"eco",ty:"c",k:"middle class",ja:"安定した経済は健全な中間層に支えられる",ch:["A stable economy depends on","a healthy middle class."]},
/* ---- pol: 政治・国際 ---- */
{c:"pol",ty:"c",k:"voter turnout",ja:"若者の投票率は低いままだ",ch:["Voter turnout among young people","remains low."]},
{c:"pol",ty:"c",k:"cooperation",ja:"地球規模の課題の解決には国際協力が不可欠だ",ch:["International cooperation is essential","to solve global issues."]},
{c:"pol",ty:"c",k:"transparent",ja:"政府はもっと透明性を高めるべきだ",ch:["The government should be","more transparent."]},
{c:"pol",ty:"c",k:"cornerstone",ja:"言論の自由は民主主義の礎だ",ch:["Freedom of speech is","a cornerstone of democracy."]},
{c:"pol",ty:"c",k:"world stage",ja:"日本は国際舞台でもっと大きな役割を果たすべきだ",ch:["Japan should play a bigger role","on the world stage."]},
{c:"pol",ty:"c",k:"short-term gains",ja:"政治判断は目先の利益を優先しがちだ",ch:["Political decisions often prioritize","short-term gains."]},
{c:"pol",ty:"c",k:"diplomacy",ja:"軍事行動より外交の方が望ましい",ch:["Diplomacy is preferable","to military action."]},
{c:"pol",ty:"c",k:"divisive",ja:"移民政策は意見が割れる問題だ",ch:["Immigration policy is","a divisive issue."]},
{c:"pol",ty:"c",k:"duty",ja:"先進国には途上国を支援する義務がある",ch:["Developed countries have a duty","to support developing nations."]},
{c:"pol",ty:"c",k:"public opinion",ja:"世論は政策立案者に圧力をかけられる",ch:["Public opinion can put pressure","on policymakers."]},
{c:"pol",ty:"c",k:"complicated",ja:"両国は複雑な関係にある",ch:["The two countries have","a complicated relationship."]},
{c:"pol",ty:"c",k:"taken for granted",ja:"平和を当たり前と思ってはいけない",ch:["Peace should never be","taken for granted."]},
{c:"pol",ty:"c",k:"voting age",ja:"選挙年齢の引き下げは政治参加を促す",ch:["Lowering the voting age","encourages political participation."]},
{c:"pol",ty:"c",k:"global solutions",ja:"地球規模の課題には地球規模の解決策が要る",ch:["Global challenges require","global solutions."]},
{c:"pol",ty:"c",k:"more harm than good",ja:"その政策は益より害が大きかった",ch:["The policy did","more harm than good."]},
{c:"pol",ty:"c",k:"accountable",ja:"政治家は公約に責任を持つべきだ",ch:["Politicians should be held accountable","for their promises."]},
/* ---- mda: メディア・社会 ---- */
{c:"mda",ty:"c",k:"believe",ja:"ネットで読んだことを鵜呑みにしてはいけない",ch:["You shouldn't believe everything","you read online."]},
{c:"mda",ty:"c",k:"exaggerate",ja:"メディアは物事を誇張しがちだ",ch:["The media tends to","exaggerate things."]},
{c:"mda",ty:"c",k:"undermines trust in",ja:"フェイクニュースは報道への信頼を損なう",ch:["Fake news undermines","trust in journalism."]},
{c:"mda",ty:"c",k:"given everyone a voice",ja:"SNSはすべての人に発言の場を与えた",ch:["Social media has given","everyone a voice."]},
{c:"mda",ty:"c",k:"privacy",ja:"デジタル時代にプライバシーを守るのは難しい",ch:["Privacy is hard to protect","in the digital age."]},
{c:"mda",ty:"c",k:"influence",ja:"有名人は若者に強い影響力を持つ",ch:["Celebrities have a strong influence","on young people."]},
{c:"mda",ty:"c",k:"multiple sources",ja:"情報は複数の情報源で確認することが大切だ",ch:["It's important to check information","from multiple sources."]},
{c:"mda",ty:"c",k:"losing readers",ja:"紙の新聞は読者を失いつつある",ch:["Traditional newspapers","are losing readers."]},
{c:"mda",ty:"c",k:"shape",ja:"広告は思った以上に私たちの欲望を形づくる",ch:["Advertising shapes our desires","more than we realize."]},
{c:"mda",ty:"c",k:"ruin",ja:"SNS上のさらし行為は人の人生を壊しかねない",ch:["Public shaming on social media","can ruin lives."]},
{c:"mda",ty:"c",k:"conflicts with",ja:"知る権利はプライバシーと衝突することがある",ch:["The right to know sometimes","conflicts with privacy."]},
{c:"mda",ty:"c",k:"media literacy",ja:"メディアリテラシーは学校で教えるべきだ",ch:["Media literacy should be","taught at school."]},
{c:"mda",ty:"c",k:"mislead",ja:"扇情的な見出しはクリックを集めるが読者を惑わす",ch:["Sensational headlines attract clicks","but mislead readers."]},
{c:"mda",ty:"c",k:"freedom of the press",ja:"報道の自由は守られなければならない",ch:["Freedom of the press","must be protected."]},
/* ---- biz: 仕事・会議 ---- */
{c:"biz",ty:"s",k:"get down to",ja:"さて、本題に入りましょう",ch:["Let's get down","to business."]},
{c:"biz",ty:"s",k:"move on",ja:"次の議題に移りましょうか",ch:["Shall we move on","to the next item?"]},
{c:"biz",ty:"s",k:"clarify",ja:"確認ですが、正確にはどういう意味ですか",ch:["Just to clarify,","what exactly","do you mean?"]},
{c:"biz",ty:"s",k:"jump in",ja:"ちょっと割り込んでもいいですか",ch:["Can I","jump in here?"]},
{c:"biz",ty:"s",k:"get back to",ja:"その件は後ほど回答させてください",ch:["Let me get back to you","on that."]},
{c:"biz",ty:"s",k:"keep you posted",ja:"進捗は随時共有します",ch:["I'll keep","you posted."]},
{c:"biz",ty:"s",k:"walk me through",ja:"手順を順を追って説明してもらえますか",ch:["Could you walk me through","the process?"]},
{c:"biz",ty:"s",k:"touch base",ja:"来週早々に軽くすり合わせましょう",ch:["Let's touch base","early next week."]},
{c:"biz",ty:"s",k:"beyond the scope",ja:"それはこの会議の範囲外ですね",ch:["That's beyond the scope","of this meeting."]},
{c:"biz",ty:"s",k:"back burner",ja:"この件はいったん後回しにしましょう",ch:["Let's put this issue","on the back burner."]},
{c:"biz",ty:"s",k:"wrap up",ja:"時間がないのでまとめに入りましょう",ch:["We're running out of time,","so let's wrap up."]},
{c:"biz",ty:"s",k:"elaborate",ja:"その点をもう少し詳しく話してもらえますか",ch:["Could you elaborate","on that point?"]},
{c:"biz",ty:"s",k:"thoughts",ja:"この件、皆さんの考えを聞かせてください",ch:["I'd like to hear","everyone's thoughts","on this."]},
{c:"biz",ty:"s",k:"pros and cons",ja:"決める前に利点と欠点を比較検討しよう",ch:["Let's weigh the pros and cons","before deciding."]},
{c:"biz",ty:"s",k:"meet the deadline",ja:"何としても締め切りは守る必要がある",ch:["We need to meet the deadline","no matter what."]},
{c:"biz",ty:"s",k:"feasible",ja:"残念ながらその予算では実現困難です",ch:["I'm afraid that's not feasible","within the budget."]},
{c:"biz",ty:"s",k:"devil's advocate",ja:"あえて反対の立場から言わせてください",ch:["Let me play devil's advocate","for a moment."]},
{c:"biz",ty:"s",k:"offline",ja:"この件は会議の外で個別に話しませんか",ch:["Can we take","this offline?"]},
{c:"biz",ty:"s",k:"add",ja:"何か付け加えたい人はいますか",ch:["Does anyone have","anything to add?"]},
{c:"biz",ty:"s",k:"go over",ja:"要点をもう一度おさらいしましょう",ch:["Let's go over","the main points","once more."]},
{c:"biz",ty:"s",k:"follow-up",ja:"会議のあとフォローアップのメールを送ります",ch:["I'll send you a follow-up email","after the meeting."]},
{c:"biz",ty:"s",k:"off track",ja:"すみません、話が逸れてきています",ch:["Sorry to interrupt,","but we're getting","off track."]},
{c:"biz",ty:"s",k:"speak up",ja:"(オンライン)よく聞こえないので大きめの声でお願いします",ch:["Could you speak up a little?","I can't hear you well."]},
{c:"biz",ty:"s",k:"breaking up",ja:"(オンライン)音声が途切れています。もう一度お願いします",ch:["You're breaking up.","Could you repeat that?"]},
{c:"biz",ty:"s",k:"schedule",ja:"フォローアップの会議を設定しましょう",ch:["Let's schedule","a follow-up meeting."]},
{c:"biz",ty:"s",k:"give me a hand",ja:"これ、手を貸してもらえないかと思いまして",ch:["I was wondering if","you could give me a hand","with this."]},
{c:"biz",ty:"s",k:"extend",ja:"締め切りを延ばしていただくことは可能ですか",ch:["Would it be possible","to extend the deadline?"]},
{c:"biz",ty:"s",k:"appreciate",ja:"金曜までにご返信いただけるとありがたいです",ch:["I'd appreciate it if","you could reply","by Friday."]},
{c:"biz",ty:"s",k:"taking the time",ja:"お時間をいただきありがとうございます",ch:["Thank you for taking the time","to meet with me."]},
{c:"biz",ty:"s",k:"same page",ja:"認識が揃っているか確認させてください",ch:["Let me make sure","we're on the same page."]},
{c:"biz",ty:"s",k:"win-win",ja:"これは双方にとってウィンウィンです",ch:["It's a win-win situation","for both sides."]},
{c:"biz",ty:"s",k:"cross that bridge",ja:"それはその時が来たら考えましょう",ch:["We'll cross that bridge","when we come to it."]},
{c:"biz",ty:"s",k:"reinvent the wheel",ja:"一から作り直す必要はありません",ch:["Let's not","reinvent the wheel."]},
{c:"biz",ty:"s",k:"long story short",ja:"かいつまんで言うと、プロジェクトは中止になった",ch:["To make a long story short,","the project was canceled."]},
/* ---- sm: 雑談(英会話レッスンの冒頭・つなぎ) ---- */
{c:"sm",ty:"s",k:"week",ja:"今週ここまでどんな感じ?",ch:["How's your week been","so far?"]},
{c:"sm",ty:"s",k:"ages",ja:"久しぶり! 元気にしてた?",ch:["It's been ages!","How have you been?"]},
{c:"sm",ty:"s",k:"meaning to",ja:"その新しいカフェ、ずっと行こうと思ってたんだ",ch:["I've been meaning to try","that new café."]},
{c:"sm",ty:"s",k:"speaking of",ja:"そういえば、あの映画観た?",ch:["Speaking of which,","have you seen that movie?"]},
{c:"sm",ty:"s",k:"remind",ja:"それで京都旅行を思い出したよ",ch:["That reminds me of","my trip to Kyoto."]},
{c:"sm",ty:"s",k:"into",ja:"最近、野球観戦にハマってるんだ",ch:["I'm really into","watching baseball","these days."]},
{c:"sm",ty:"s",k:"cup of tea",ja:"それはあまり好みじゃないな",ch:["It's not really","my cup of tea."]},
{c:"sm",ty:"s",k:"could really use",ja:"休暇が本気で欲しい",ch:["I could really use","a vacation."]},
{c:"sm",ty:"s",k:"time flies",ja:"時間が経つのは早いね",ch:["Time flies,","doesn't it?"]},
{c:"sm",ty:"s",k:"swamped",ja:"最近仕事に忙殺されてるんだ",ch:["I've been swamped","with work lately."]},
{c:"sm",ty:"s",k:"unwind",ja:"息抜きには何をしてるの?",ch:["What do you do","to unwind?"]},
{c:"sm",ty:"s",k:"looking forward",ja:"連休が楽しみだ",ch:["I'm looking forward to","the long weekend."]},
{c:"sm",ty:"s",k:"never guess",ja:"昨日何があったと思う?",ch:["You'll never guess","what happened to me","yesterday."]},
{c:"sm",ty:"s",k:"slipped my mind",ja:"すっかり忘れてたよ",ch:["It slipped my mind","completely."]},
{c:"sm",ty:"s",k:"long story short",ja:"要するに、終電を逃したんだ",ch:["Long story short,","we missed the last train."]},
{c:"sm",ty:"s",k:"know the feeling",ja:"その気持ち、わかるよ",ch:["I know","the feeling."]},
{c:"sm",ty:"s",k:"sounds like",ja:"それはすごく楽しそうだね",ch:["That sounds like","a lot of fun."]},
{c:"sm",ty:"s",k:"go",ja:"プレゼンはどうだった?",ch:["How did your","presentation go?"]},
{c:"sm",ty:"s",k:"rumor",ja:"噂では2人は結婚するらしい",ch:["Rumor has it","they're getting married."]},
{c:"sm",ty:"s",k:"morning person",ja:"自分は朝型じゃないんだ",ch:["I'm not","a morning person."]},
{c:"sm",ty:"s",k:"blessing in disguise",ja:"あれは不幸に見えて実は幸運だった",ch:["It was a blessing","in disguise."]},
{c:"sm",ty:"s",k:"grab a bite",ja:"会議の前に軽く食べようよ",ch:["Let's grab a bite","before the meeting."]},
{c:"sm",ty:"s",k:"tight",ja:"今週は予定がかなり詰まってるんだ",ch:["My schedule is pretty tight","this week."]},
{c:"sm",ty:"s",k:"better late",ja:"遅くてもやらないよりマシでしょ?",ch:["Better late","than never, right?"]},
/* ---- vp: 動詞の型(v5.4.0・実機FB「make/help/forceばかりで子供っぽくなる」への回答) ----
   正確な動詞は「動詞+目的語+前置詞/補語」が1セット(項構造)。ptにその一般形を持たせ、
   答え合わせで「型」として見せる=1文の暗記が型の獲得になる。jaは「〜させる/おかげで/せいで」と
   直訳したくなる意図で書く(そこでmakeに逃げず正確な動詞を取り出す訓練) */
{c:"vp",ty:"c",k:"enabled her to",pt:"enable 人 to do(〜のおかげで…できる)",ja:"奨学金のおかげで彼女は留学できた",ch:["The scholarship","enabled her to","study abroad."]},
{c:"vp",ty:"c",k:"prevented us from going",pt:"prevent 人 from -ing(〜のせいで…できない)",ja:"大雨のせいで私たちは外出できなかった",ch:["The heavy rain","prevented us from","going out."]},
{c:"vp",ty:"c",k:"encouraged me to",pt:"encourage 人 to do(背中を押す)",ja:"彼の助言に背中を押されて挑戦した",ch:["His advice","encouraged me to","take on the challenge."]},
{c:"vp",ty:"c",k:"discourage young people from buying",pt:"discourage 人 from -ing(〜する気をなくさせる)",ja:"価格の高さが若者を車の購入から遠ざけている",ch:["High prices discourage","young people from","buying cars."]},
{c:"vp",ty:"c",k:"allows users to",pt:"allow 人 to do(〜で…できるようになる)",ja:"そのアプリで支出を記録できる",ch:["The app","allows users to","track their spending."]},
{c:"vp",ty:"c",k:"provides refugees with",pt:"provide 人 with 物(人に物を提供する)",ja:"政府は難民に食料と住まいを提供している",ch:["The government","provides refugees with","food and shelter."]},
{c:"vp",ty:"c",k:"cause employees to",pt:"cause 人 to do(〜を引き起こす)",ja:"ストレスは社員の燃え尽きを引き起こしうる",ch:["Stress can","cause employees to","burn out."]},
{c:"vp",ty:"c",k:"led the minister to",pt:"lead 人 to do(〜に追い込む・つながる)",ja:"そのスキャンダルで大臣は辞任に追い込まれた",ch:["The scandal","led the minister to","resign."]},
{c:"vp",ty:"c",k:"resulted in",pt:"result in 名詞(〜という結果を招く)",ja:"計画の甘さが大損失を招いた",ch:["Poor planning","resulted in","a huge loss."]},
{c:"vp",ty:"c",k:"contributed to",pt:"contribute to 名詞(〜に貢献する)",ja:"ボランティアがイベントの成功に貢献した",ch:["Volunteers","contributed to","the success of the event."]},
{c:"vp",ty:"c",k:"reminds me of",pt:"remind 人 of 名詞(〜を思い出させる)",ja:"この写真を見ると学生時代を思い出す",ch:["This photo","reminds me of","my school days."]},
{c:"vp",ty:"c",k:"convinced her boss to",pt:"convince 人 to do(説得して〜させる)",ja:"彼女は上司を説得して計画を変えさせた",ch:["She convinced","her boss to","change the plan."]},
{c:"vp",ty:"c",k:"urged the government to",pt:"urge 人 to do(強く求める)",ja:"彼らは政府に対応を強く求めた",ch:["They urged","the government to","take action."]},
{c:"vp",ty:"c",k:"equips students with",pt:"equip 人 with 物(身につけさせる)",ja:"その講座は実践的スキルを身につけさせてくれる",ch:["The course","equips students with","practical skills."]},
{c:"vp",ty:"c",k:"requires companies to",pt:"require 人 to do(義務づける)",ja:"新しい法律は企業にデータ開示を義務づけている",ch:["The new law","requires companies to","disclose the data."]},
{c:"vp",ty:"c",k:"kept me from concentrating",pt:"keep 人 from -ing(〜のせいで…できない)",ja:"騒音のせいで集中できなかった",ch:["The noise","kept me from","concentrating."]},
{c:"vp",ty:"c",k:"exposes you to",pt:"expose 人 to 名詞(〜に触れさせる)",ja:"幅広い読書は新しい考えに触れさせてくれる",ch:["Reading widely","exposes you to","new ideas."]},
{c:"vp",ty:"c",k:"aims to",pt:"aim to do(〜を目指す)",ja:"その事業は食品ロス削減を目指している",ch:["The program","aims to","reduce food waste."]},
{c:"vp",ty:"c",k:"banned employees from using",pt:"ban 人 from -ing(禁じる)",ja:"会社は社員にそのアプリの使用を禁じた",ch:["The company banned","employees from","using the app."]},
{c:"vp",ty:"c",k:"inspired many girls to",pt:"inspire 人 to do(〜する気にさせる)",ja:"彼女の成功が多くの少女を理系に向かわせた",ch:["Her success","inspired many girls to","study science."]},
{c:"vp",ty:"c",k:"compares Japan with",pt:"compare A with B(比べる)",ja:"この図は日本を他国と比べている",ch:["The chart","compares Japan with","other countries."]},
{c:"vp",ty:"c",k:"attribute my progress to",pt:"attribute A to B(Aの原因はBだと考える)",ja:"上達したのは毎日の練習のおかげだと思う",ch:["I attribute","my progress to","daily practice."]},
{c:"vp",ty:"c",k:"offers guests",pt:"offer 人 物(人に物を出す)",ja:"そのホテルは宿泊客に無料の朝食を出す",ch:["The hotel","offers guests","a free breakfast."]},
{c:"vp",ty:"c",k:"applies to",pt:"apply to 名詞(〜に当てはまる)",ja:"その規則は全員に当てはまる",ch:["The rule","applies to","all members."]},
{c:"vp",ty:"c",k:"deals with",pt:"deal with 名詞(〜を扱う・に対処する)",ja:"そのセミナーは職場のコミュニケーションを扱う",ch:["The seminar","deals with","workplace communication."]},
{c:"vp",ty:"c",k:"succeeded in cutting",pt:"succeed in -ing(〜に成功する)",ja:"チームはコスト半減に成功した",ch:["The team","succeeded in","cutting costs by half."]},
{c:"vp",ty:"c",k:"benefited a lot from",pt:"benefit from 名詞(〜の恩恵を受ける)",ja:"彼女のフィードバックには大いに助けられた",ch:["I benefited","a lot from","her feedback."]},
{c:"vp",ty:"c",k:"turned beginners into",pt:"turn A into B(AをBに変える)",ja:"その研修は初心者を自信ある話し手に変えた",ch:["The workshop","turned beginners into","confident speakers."]},
/* v5.5.0拡充: 汎用性の高い動詞の型(判断・比較系/対処系/感情・対人系/結果・変化系) */
{c:"vp",ty:"c",k:"prefer working from home to",pt:"prefer A to B(BよりAがいい)",ja:"通勤より在宅勤務のほうが好きだ",ch:["I prefer","working from home","to commuting."]},
{c:"vp",ty:"c",k:"regard AI as",pt:"regard A as B(AをBとみなす)",ja:"多くの人はAIを脅威とみなしている",ch:["Many people","regard AI as","a threat."]},
{c:"vp",ty:"c",k:"described the plan as",pt:"describe A as B(AをBだと評する)",ja:"批評家たちはその計画を非現実的だと評した",ch:["Critics","described the plan as","unrealistic."]},
{c:"vp",ty:"c",k:"define success as",pt:"define A as B(AをBと定義する)",ja:"私たちは成功を「成長し続けること」と定義する",ch:["We define","success as","continuous growth."]},
{c:"vp",ty:"c",k:"suffer from",pt:"suffer from 名詞(〜に悩まされる)",ja:"多くの働き手が慢性的なストレスに悩まされている",ch:["Many workers","suffer from","chronic stress."]},
{c:"vp",ty:"c",k:"struggle to attract",pt:"struggle to do(なかなか〜できない)",ja:"中小企業は若い人材の確保に苦戦している",ch:["Small firms","struggle to attract","young talent."]},
{c:"vp",ty:"c",k:"managed to",pt:"manage to do(なんとか〜できた)",ja:"なんとか期限までに報告書を仕上げた",ch:["We managed to","finish the report","on time."]},
{c:"vp",ty:"c",k:"failed to",pt:"fail to do(〜できなかった・しなかった)",ja:"そのキャンペーンは注目を集められなかった",ch:["The campaign","failed to","attract attention."]},
{c:"vp",ty:"c",k:"tend to",pt:"tend to do(〜しがちだ)",ja:"人は自分の能力を過大評価しがちだ",ch:["People tend to","overestimate","their abilities."]},
{c:"vp",ty:"c",k:"hesitate to",pt:"hesitate to do(遠慮なく〜して)",ja:"遠慮なく助けを求めてください",ch:["Don't hesitate to","ask me for help."]},
{c:"vp",ty:"c",k:"insisted on paying",pt:"insist on -ing(〜すると言って聞かない)",ja:"彼は夕食代を払うと言って聞かなかった",ch:["He insisted on","paying for dinner."]},
{c:"vp",ty:"c",k:"objected to",pt:"object to 名詞(〜に反対する)",ja:"地元住民はその建設計画に反対した",ch:["Local residents","objected to","the construction plan."]},
{c:"vp",ty:"c",k:"cope with",pt:"cope with 名詞(〜にうまく対処する)",ja:"ストレスにうまく対処する方法が必要だ",ch:["We need strategies","to cope with","stress."]},
{c:"vp",ty:"c",k:"adapt to",pt:"adapt to 名詞(〜に適応する)",ja:"企業は消費者ニーズの変化に適応しなければならない",ch:["Companies must","adapt to","changing consumer needs."]},
{c:"vp",ty:"c",k:"accused the company of",pt:"accuse 人 of 名詞(〜だと非難する)",ja:"メディアはその企業を真実の隠蔽で非難した",ch:["The media","accused the company of","hiding the truth."]},
{c:"vp",ty:"c",k:"blame others for",pt:"blame 人 for 事(人のせいにする)",ja:"自分のミスを人のせいにしてはいけない",ch:["Don't blame","others for","your mistakes."]},
{c:"vp",ty:"c",k:"praised her for",pt:"praise 人 for 事(〜を褒める)",ja:"先生は彼女の努力を褒めた",ch:["The teacher","praised her for","her effort."]},
{c:"vp",ty:"c",k:"thank you enough for",pt:"can't thank 人 enough(感謝してもしきれない)",ja:"あなたの支えには感謝してもしきれない",ch:["I can't","thank you enough for","your support."]},
{c:"vp",ty:"c",k:"apologize for",pt:"apologize for 名詞(〜を詫びる)",ja:"混乱させてしまい申し訳ありません",ch:["I apologize for","the confusion."]},
{c:"vp",ty:"c",k:"congratulate you on",pt:"congratulate 人 on 事(〜おめでとう)",ja:"昇進、おめでとうございます",ch:["Let me","congratulate you on","your promotion."]},
{c:"vp",ty:"c",k:"keep me informed of",pt:"keep 人 informed of(随時知らせる)",ja:"何か変更があれば随時知らせてください",ch:["Please keep me","informed of","any changes."]},
{c:"vp",ty:"c",k:"warned us against relying",pt:"warn 人 against -ing(〜しないよう警告する)",ja:"専門家は情報源を1つに頼らないよう警告した",ch:["Experts warned us","against relying on","a single source."]},
{c:"vp",ty:"c",k:"protect consumers from",pt:"protect 人 from 名詞(〜から守る)",ja:"規制は消費者を詐欺から守っている",ch:["Regulations","protect consumers from","fraud."]},
{c:"vp",ty:"c",k:"distinguish facts from",pt:"distinguish A from B(AとBを区別する)",ja:"事実と意見を区別するのは難しい",ch:["It's hard to","distinguish facts from","opinions."]},
{c:"vp",ty:"c",k:"associate success with",pt:"associate A with B(結びつけて考える)",ja:"人は成功をお金と結びつけがちだ",ch:["People often","associate success with","money."]},
{c:"vp",ty:"c",k:"replaced paper forms with",pt:"replace A with B(AをBに置き換える)",ja:"その会社は紙の書類をオンラインシステムに置き換えた",ch:["The firm replaced","paper forms with","an online system."]},
{c:"vp",ty:"c",k:"devotes her weekends to",pt:"devote A to B(AをBに注ぐ)",ja:"彼女は週末をボランティアに充てている",ch:["She devotes","her weekends to","volunteering."]},
{c:"vp",ty:"c",k:"committed to cutting",pt:"commit to -ing(〜すると約束する)",ja:"その会社は2030年までの排出削減を約束した",ch:["The company","committed to cutting","emissions by 2030."]},
{c:"vp",ty:"c",k:"take cultural differences into account",pt:"take A into account(考慮に入れる)",ja:"文化の違いを考慮に入れるべきだ",ch:["We should take","cultural differences","into account."]},
{c:"vp",ty:"c",k:"translate into",pt:"translate into 名詞(〜に結びつく)",ja:"努力が結果に結びつくとは限らない",ch:["Effort doesn't always","translate into","results."]},
{c:"vp",ty:"c",k:"stem from",pt:"stem from 名詞(〜に起因する)",ja:"多くの問題はコミュニケーション不足に起因する",ch:["Many problems","stem from","poor communication."]},
{c:"vp",ty:"c",k:"refrain from using",pt:"refrain from -ing(〜を控える)",ja:"ここでは携帯電話の使用をお控えください",ch:["Please refrain from","using your phone","here."]},
{c:"vp",ty:"c",k:"get used to",pt:"get used to 名詞(〜に慣れる)",ja:"リモートワークに慣れるまでしばらくかかった",ch:["It took me a while","to get used to","remote work."]},
{c:"vp",ty:"c",k:"ended up canceling",pt:"end up -ing(結局〜することになる)",ja:"結局、旅行は取りやめることになった",ch:["We ended up","canceling the trip."]},
/* ---- ims: 無生物主語(v5.4.0) ----
   「〜のおかげで/せいで/を見ると」を、モノ・経験・数字を主語にして言う=添削後の英語の型。
   日本語は無生物主語を避けるため意識的に訓練しないと出てこない */
{c:"ims",ty:"c",k:"shows",pt:"モノ show 事(グラフが〜を示す)",ja:"このグラフから物価の急上昇が分かる",ch:["This graph shows","a sharp rise","in prices."]},
{c:"ims",ty:"c",k:"suggests that",pt:"モノ suggest that(データが示唆する)",ja:"データを見ると政策は機能していそうだ",ch:["The data suggests that","the policy is working."]},
{c:"ims",ty:"c",k:"taught me",pt:"経験 teach 人 事(〜で学んだ)",ja:"海外生活で家族の大切さを学んだ",ch:["Living abroad","taught me","the value of family."]},
{c:"ims",ty:"c",k:"cost us",pt:"モノ cost 人 物(〜のせいで失った)",ja:"その遅れで私たちは契約を失った",ch:["The delay","cost us","the contract."]},
{c:"ims",ty:"c",k:"will take you to",pt:"モノ take 人 to 場所(〜すれば着く)",ja:"10分歩けば駅に着く",ch:["A ten-minute walk","will take you to","the station."]},
{c:"ims",ty:"c",k:"brought you to",pt:"モノ bring 人 to(来た理由を聞く)",ja:"どうして日本に来たんですか(自然な聞き方)",ch:["What brought you","to Japan?"]},
{c:"ims",ty:"c",k:"reveals",pt:"モノ reveal 事(よく見ると分かる)",ja:"よく見るといくつか問題が見えてくる",ch:["A closer look","reveals","some problems."]},
{c:"ims",ty:"c",k:"will save you",pt:"モノ save 人 時間/手間(〜すれば省ける)",ja:"5分調べれば何時間もの作業を節約できる",ch:["Five minutes of research","will save you","hours of work."]},
{c:"ims",ty:"c",k:"woke me up",pt:"モノ wake 人 up(〜で目が覚めた)",ja:"コーヒーの香りで目が覚めた",ch:["The smell of coffee","woke me up."]},
{c:"ims",ty:"c",k:"left me no time to",pt:"モノ leave 人 no time to do(〜のせいで時間がない)",ja:"予定が詰まっていて運動する時間がなかった",ch:["The heavy schedule","left me no time to","exercise."]},
{c:"ims",ty:"c",k:"points to",pt:"モノ point to 名詞(〜を指し示す)",ja:"証拠は別の結論を指し示している",ch:["The evidence","points to","a different conclusion."]},
{c:"ims",ty:"c",k:"gave me a new perspective",pt:"経験 give 人 視点/機会(〜で得た)",ja:"この経験で新しい視点を得た",ch:["This experience","gave me","a new perspective."]},
{c:"ims",ty:"c",k:"tell a different story",pt:"モノ tell a story(実態を物語る)",ja:"数字は別の実態を物語っている",ch:["The figures","tell a different story."]},
{c:"ims",ty:"c",k:"gives everyone access to",pt:"モノ give 人 access to(〜で使えるようになる)",ja:"ネットのおかげで誰もが情報にアクセスできる",ch:["The Internet","gives everyone access to","information."]},
{c:"ims",ty:"c",k:"told me",pt:"モノ tell 人 that(見て分かった)",ja:"顔を見た瞬間、何かあったと分かった",ch:["One look at his face","told me","something was wrong."]},
{c:"ims",ty:"c",k:"keeps your memory fresh",pt:"モノ keep O C(〜に保つ)",ja:"定期的な復習が記憶を新鮮に保つ",ch:["Regular review","keeps your memory fresh."]},
/* v5.5.0拡充: 会話・報告の両方で回せる無生物主語(データ系/経験系/慣用系) */
{c:"ims",ty:"c",k:"highlights",pt:"モノ highlight 事(〜を浮き彫りにする)",ja:"その報告書は改革の必要性を浮き彫りにしている",ch:["The report highlights","the need for reform."]},
{c:"ims",ty:"c",k:"confirm",pt:"モノ confirm 事(〜を裏付ける)",ja:"結果は当初の仮説を裏付けている",ch:["The results confirm","our initial hypothesis."]},
{c:"ims",ty:"c",k:"found that",pt:"調査 find that(調査で〜と分かった)",ja:"調査では大半の利用者が満足していると分かった",ch:["The survey found that","most users were satisfied."]},
{c:"ims",ty:"c",k:"will give you",pt:"モノ give 人 答え(〜すれば分かる)",ja:"ちょっと検索すれば答えは分かるよ",ch:["A quick search","will give you","the answer."]},
{c:"ims",ty:"c",k:"entitles you to",pt:"モノ entitle 人 to(〜の権利を与える)",ja:"このチケットで飲み物が1杯無料になる",ch:["This ticket","entitles you to","a free drink."]},
{c:"ims",ty:"c",k:"will do you good",pt:"モノ do 人 good(〜のためになる)",ja:"ぐっすり眠れば調子が良くなるよ",ch:["A good night's sleep","will do you good."]},
{c:"ims",ty:"c",k:"captures",pt:"モノ capture 事(〜をよく捉えている)",ja:"この写真はあの時代の空気をよく捉えている",ch:["The photo captures","the mood of the era."]},
{c:"ims",ty:"c",k:"links lack of sleep to",pt:"研究 link A to B(AとBを関連づける)",ja:"その研究は睡眠不足と体重増加を関連づけている",ch:["The study links","lack of sleep to","weight gain."]},
{c:"ims",ty:"c",k:"will spare you",pt:"モノ spare 人 手間(〜すれば手間が省ける)",ja:"この近道でかなりの手間が省けるよ",ch:["This shortcut","will spare you","a lot of trouble."]},
{c:"ims",ty:"c",k:"opened my eyes to",pt:"経験 open 人's eyes to(目を開かせる)",ja:"その経験が新しい世界に目を開かせてくれた",ch:["The experience","opened my eyes to","a new world."]},
{c:"ims",ty:"c",k:"makes you think",pt:"What makes 人 do?(なぜ?の自然な聞き方)",ja:"どうしてそう思うんですか(自然な聞き方)",ch:["What makes you","think so?"]},
{c:"ims",ty:"c",k:"ring a bell",pt:"モノ ring a bell(聞き覚えがある)",ja:"その単語には聞き覚えがないな",ch:["That word","doesn't ring a bell."]},
{c:"ims",ty:"c",k:"speak for themselves",pt:"数字 speak for themselves(すべてを物語る)",ja:"数字がすべてを物語っている",ch:["The numbers","speak for themselves."]},
{c:"ims",ty:"c",k:"tells me",pt:"Something tell 人(どうも〜な気がする)",ja:"どうもこれは偶然じゃない気がする",ch:["Something tells me","this isn't a coincidence."]},
{c:"ims",ty:"c",k:"requires",pt:"モノ require 名詞(〜には…が要る)",ja:"この仕事にはかなりの忍耐が要る",ch:["This job requires","a lot of patience."]},
{c:"ims",ty:"c",k:"explains a lot",pt:"モノ explain(それで合点がいく)",ja:"それで合点がいった",ch:["That","explains a lot."]},
{c:"ims",ty:"c",k:"ran over by",pt:"会議 run over(予定より長引く)",ja:"会議は30分長引いた",ch:["The meeting","ran over by","thirty minutes."]},
{c:"ims",ty:"c",k:"crossed my mind",pt:"考え cross 人's mind(頭をよぎる)",ja:"その考えは思いつきもしなかった",ch:["The idea","never crossed","my mind."]},
{c:"ims",ty:"c",k:"took my breath away",pt:"モノ take 人's breath away(息をのむ)",ja:"その景色に思わず息をのんだ",ch:["The view","took my breath away."]},
{c:"ims",ty:"c",k:"changed the way",pt:"モノ change the way 人 do(〜のあり方を変える)",ja:"パンデミックは私たちの働き方を変えた",ch:["The pandemic","changed the way","we work."]},
];
/* en(SRS記録のキー)はチャンクから導出する ─ 「保存せず導出」+表記と並べ替えの正解が常に一致 */
PHRASES.forEach(p=>{ p.en=p.ch.join(" "); });
const byPhr={}; PHRASES.forEach(p=>byPhr[p.en]=p);
