"use strict";
/* ================= 語源(語根・接辞)辞書 =================
   綴りからのパターンマッチ+誤タグ抑制リストで語源タグを決定的に導出(保存せず導出)。
   ファミリー一覧は目視レビュー済み(誤りを見つけたら BLOCK に追記)。
   語根タグは「共鳴」(同語根が同じ節に並ぶと強化)の判定にも使う。接頭辞は表示のみ。 */
const ROOT_DEFS=[
  {t:"spec", m:"見る", pat:["spect","spec","spic"]},
  {t:"dict", m:"言う", pat:["dict"]},
  {t:"port", m:"運ぶ", pat:["port"]},
  {t:"duct", m:"導く", pat:["duct","duce"]},
  {t:"ject", m:"投げる", pat:["ject"]},
  {t:"mit", m:"送る", pat:["mitt","miss","mit"]},
  {t:"scrib", m:"書く", pat:["scrib","script"]},
  {t:"vert", m:"回す・向ける", pat:["vert","vers"]},
  {t:"cess", m:"行く・譲る", pat:["cede","ceed","cess"]},
  {t:"fer", m:"運ぶ", pat:["fer"]},
  {t:"tract", m:"引く", pat:["tract"]},
  {t:"struct", m:"建てる", pat:["struct"]},
  {t:"form", m:"形", pat:["form"]},
  {t:"press", m:"押す", pat:["press"]},
  {t:"pos", m:"置く", pat:["pose","posit","pound"]},
  {t:"tain", m:"保つ", pat:["tain","tinen","tenan","tenac","tenet"]},
  {t:"voc", m:"呼ぶ・声", pat:["voc","vok"]},
  {t:"gen", m:"生む・種族", pat:["gen"]},
  {t:"mort", m:"死", pat:["mort"]},
  {t:"viv", m:"生きる", pat:["viv","vital","vita","viab"]},
  {t:"aud", m:"聞く", pat:["aud"]},
  {t:"vis", m:"見る", pat:["vis","vid"]},
  {t:"cred", m:"信じる", pat:["cred"]},
  {t:"cur", m:"走る", pat:["curr","curs","cours"]},
  {t:"cura", m:"世話・注意", pat:["cura","curat","ccura","secur","procur"]},
  {t:"flect", m:"曲げる", pat:["flect","flex"]},
  {t:"grad", m:"歩む・段階", pat:["grad","gress"]},
  {t:"junct", m:"結ぶ", pat:["junct","join"]},
  {t:"lect", m:"選ぶ・読む・法", pat:["lect","leg"]},
  {t:"loqu", m:"話す", pat:["loqu","locut"]},
  {t:"magn", m:"大きい", pat:["magn"]},
  {t:"man", m:"手", pat:["manu","mani"]},
  {t:"nov", m:"新しい", pat:["nov"]},
  {t:"path", m:"感情・苦しみ", pat:["path"]},
  {t:"phon", m:"音", pat:["phon"]},
  {t:"rupt", m:"破る", pat:["rupt"]},
  {t:"sci", m:"知る", pat:["sci"]},
  {t:"sect", m:"切る", pat:["sect"]},
  {t:"sens", m:"感じる", pat:["sens","sent"]},
  {t:"sequ", m:"続く", pat:["sequ","secut"]},
  {t:"solv", m:"解く", pat:["solv","solut"]},
  {t:"spir", m:"息・魂", pat:["spir"]},
  {t:"stat", m:"立つ", pat:["stat","stit","stab","stan","sist"]},
  {t:"tact", m:"触れる", pat:["tact","tang","tig"]},
  {t:"tempor", m:"時", pat:["tempor"]},
  {t:"terr", m:"土地", pat:["territ","terra","terrain","terrestr","subterr"]},
  {t:"terrere", m:"怖がらせる", pat:["terrif","terribl","deterr"]},
  {t:"therm", m:"熱", pat:["therm"]},
  {t:"tort", m:"ねじる", pat:["tort"]},
  {t:"vac", m:"空の", pat:["vac","vanis","vain"]},
  {t:"ven", m:"来る", pat:["vene","vent","coven"]},
  {t:"volv", m:"回る", pat:["volv","volut"]},
  {t:"fac", m:"作る・なす", pat:["fact","fect","fic"]},
  {t:"cap", m:"つかむ", pat:["capt","cept","ceive","cip"]},
  {t:"clud", m:"閉じる", pat:["clud","clus","close"]},
  {t:"puls", m:"押す・打つ", pat:["pel","puls"]},
  {t:"pend", m:"掛ける・払う", pat:["pend","pens","penchan","ponder"]},
  {t:"plic", m:"折る・重ねる", pat:["plic","plex","ploy"]},
  {t:"rect", m:"まっすぐ", pat:["rect","reg"]},
  {t:"tend", m:"伸ばす", pat:["tend","tens","ostent"]},
  {t:"grat", m:"喜び・感謝", pat:["grat"]},
  {t:"corp", m:"体", pat:["corp"]},
  {t:"anim", m:"心・命", pat:["anim"]},
  {t:"aqua", m:"水", pat:["aqua","aqu"]},
  {t:"astr", m:"星", pat:["astr","aster"]},
  {t:"bio", m:"生命", pat:["bio"]},
  {t:"chron", m:"時", pat:["chron"]},
  {t:"dem", m:"民衆", pat:["democ","demogr","epidem","pandem"]},
  {t:"geo", m:"地球・土地", pat:["geo"]},
  {t:"graph", m:"書く", pat:["graph","gram"]},
  {t:"log", m:"言葉・学問", pat:["logy","logu"]},
  {t:"metr", m:"測る", pat:["meter","metr","mens"]},
  {t:"nym", m:"名前", pat:["nym","nomin"]},
  {t:"ped", m:"足", pat:["ped"]},
  {t:"phil", m:"愛する", pat:["phil"]},
  {t:"pot", m:"力", pat:["potent","poss"]},
  {t:"prim", m:"第一の", pat:["prim"]},
  {t:"psych", m:"心", pat:["psych"]},
  {t:"urb", m:"都市", pat:["urb"]},
  {t:"verb", m:"言葉", pat:["verb"]},
  {t:"fid", m:"信頼", pat:["fid"]},
  {t:"her", m:"くっつく", pat:["here","hes"]},
  {t:"lud", m:"遊ぶ・欺く", pat:["lud","lusi"]},
  {t:"mand", m:"命じる", pat:["mand"]},
  {t:"fort", m:"強い", pat:["fort"]},
  {t:"dur", m:"続く・硬い", pat:["dur"]},
  {t:"nat", m:"生まれる", pat:["nat","nasc"]},
  {t:"mem", m:"記憶", pat:["mem"]},
  {t:"popul", m:"人々", pat:["popul","publ"]},
  {t:"liber", m:"自由", pat:["liber"]},
  {t:"equ", m:"等しい", pat:["equi","equa"]},
  {t:"simil", m:"似ている", pat:["simil","simul","sembl"]},
  {t:"clam", m:"叫ぶ", pat:["claim","clam"]},
  {t:"don", m:"与える", pat:["donat","dot"]},
  {t:"mob", m:"動く", pat:["mob","mot","mov"]},
  {t:"clin", m:"傾く", pat:["clin"]},
  {t:"fin", m:"終わり・限界", pat:["fin"]},
  {t:"firm", m:"固い", pat:["firm"]},
  {t:"flu", m:"流れる", pat:["flu"]},
  {t:"fus", m:"注ぐ・溶ける", pat:["fus"]},
  {t:"lev", m:"軽い・上げる", pat:["lev"]},
  {t:"luc", m:"光", pat:["lucid","lumin"]},
  {t:"medi", m:"中間", pat:["medi"]},
  {t:"migr", m:"移動する", pat:["migra"]},
  {t:"noc", m:"害する", pat:["noc","nox"]},
  {t:"ora", m:"口・話す", pat:["orat","oracl"]},
  {t:"pati", m:"苦しむ・耐える", pat:["pati","passio"]},
  {t:"phan", m:"現れる・見せる", pat:["phan","phen"]},
  {t:"plen", m:"満ちた", pat:["plen","plet"]},
  {t:"prehend", m:"つかむ", pat:["prehen","pris"]},
  {t:"prob", m:"試す・証明", pat:["prob","prov"]},
  {t:"quir", m:"求める・尋ねる", pat:["quir","quis","quest"]},
  {t:"radi", m:"光線・根", pat:["radi"]},
  {t:"scend", m:"登る", pat:["scend","scens"]},
  {t:"trud", m:"押し出す", pat:["trud","trusi","truse"]},
  {t:"val", m:"強い・価値", pat:["val"]},
  {t:"veri", m:"真実", pat:["veri"]},
  {t:"vor", m:"食べる", pat:["vorac","vour","ivoro"]},
  {t:"bell", m:"戦い", pat:["belli","rebel"]},
  {t:"cid", m:"切る・殺す", pat:["cide","cis"]},
  {t:"crea", m:"生み出す", pat:["crea"]},
  {t:"cult", m:"耕す・育てる", pat:["culti","cultu"]},
  {t:"doc", m:"教える", pat:["doc"]},
  {t:"empt", m:"取る・買う", pat:["empt"]},
  {t:"greg", m:"群れ", pat:["greg"]},
  {t:"hab", m:"持つ・住む", pat:["hab","hibit"]},
  {t:"labor", m:"働く", pat:["labor"]},
  {t:"later", m:"側面", pat:["later"]},
  {t:"lig", m:"縛る", pat:["oblig","relig","liga"]},
  {t:"loc", m:"場所", pat:["loc"]},
  {t:"mut", m:"変える", pat:["mut"]},
  {t:"neg", m:"否定する", pat:["neg"]},
  {t:"oner", m:"重い(負担)", pat:["onero","onus"]},
  {t:"opt", m:"選ぶ・見る", pat:["opt"]},
  {t:"orig", m:"生じる", pat:["orig","orient"]},
  {t:"pen", m:"罰・償い", pat:["penal","puni"]},
  {t:"petit", m:"求める", pat:["petit","impet","appet","compet","petulan"]},
  {t:"plac", m:"なだめる", pat:["plac"]},
  {t:"sacr", m:"神聖な", pat:["sacr","sanct","secrat"]},
  {t:"sal", m:"跳ぶ", pat:["sault","sult","salien"]},
  {t:"scrut", m:"調べる", pat:["scrut"]},
  {t:"sed", m:"座る", pat:["sid","sess","sed"]},
  {t:"sert", m:"結ぶ・差し込む", pat:["sert"]},
  {t:"sign", m:"印", pat:["sign"]},
  {t:"son", m:"音", pat:["sonor","resona","sonat","unison","sonic"]},
  {t:"sort", m:"種類・運命", pat:["sort"]},
  {t:"spers", m:"まく", pat:["spers","spars"]},
  {t:"string", m:"縛る", pat:["string","strict","strain"]},
  {t:"tenu", m:"細い", pat:["tenu"]},
  {t:"test", m:"証言する", pat:["test"]},
  {t:"tim", m:"恐れる", pat:["timid","timor"]},
  {t:"trib", m:"与える", pat:["trib"]},
  {t:"turb", m:"かき乱す", pat:["turb"]},
  {t:"umbr", m:"影", pat:["umbr","somber","sombre"]},
  {t:"und", m:"波", pat:["unda"]},
  {t:"util", m:"使う", pat:["util","usur","usual","utensil"]},
  {t:"cord", m:"心", pat:["cord","courag"]},
  {t:"ann", m:"年", pat:["annu","enni","anniv"]},
  {t:"cern", m:"分ける", pat:["cern","cret"]},
  {t:"norm", m:"規範", pat:["norm"]},
  {t:"term", m:"境界", pat:["term"]},
  {t:"part", m:"部分", pat:["part"]},
  {t:"ward", m:"〜の方へ", pat:["ward"]},
  {t:"cogn", m:"知る", pat:["cogn","gnos","gniz","gnor"]},
  {t:"err", m:"さまよう・誤る", pat:["err"]},
  {t:"the", m:"神", pat:["theo","athei","enthus","pantheo"]},
  {t:"thes", m:"置く(ギリシャ)", pat:["thesis","thet","thesi"]},
  {t:"esthe", m:"感覚(ギリシャ)", pat:["esthet","esthesi"]},
  {t:"arch", m:"支配・最初", pat:["arch"]},
  {t:"phob", m:"恐れ", pat:["phob"]},
  {t:"morph", m:"形", pat:["morph"]},
  {t:"soph", m:"知恵", pat:["soph"]},
  {t:"scop", m:"見る(ギリシャ)", pat:["scop"]},
  {t:"crat", m:"支配", pat:["crat","cracy"]},
  {t:"polis", m:"都市(ギリシャ)", pat:["polis","polit","polic"]},
  {t:"typ", m:"型", pat:["typ"]},
  {t:"techn", m:"技術", pat:["techn"]},
  {t:"top", m:"場所(ギリシャ)", pat:["topi","topo"]},
  {t:"cosm", m:"宇宙・秩序", pat:["cosm"]},
  {t:"hydr", m:"水(ギリシャ)", pat:["hydr"]},
  {t:"nomy", m:"法・分配(ギリシャ)", pat:["nomy","nomic","nomous"]},
  {t:"phys", m:"自然", pat:["phys"]},
  {t:"dox", m:"意見", pat:["dox"]},
  {t:"tom", m:"切る(ギリシャ)", pat:["tomy","atom","epitom"]},
  {t:"phras", m:"言い回し", pat:["phras"]},
  {t:"vinc", m:"勝つ", pat:["vinc","vict","vanqu"]},
  {t:"vad", m:"行く", pat:["vade","vasi","vasio"]},
  {t:"vag", m:"さまよう", pat:["vagu","vagab","vagr","travag"]},
  {t:"vol", m:"意志", pat:["volunt","volen","voliti"]},
  {t:"via", m:"道", pat:["obvi","devi","trivi","previ","convey","voyag","pervi"]},
  {t:"vulg", m:"大衆", pat:["vulg"]},
  {t:"rog", m:"尋ねる・要求", pat:["rog"]},
  {t:"put", m:"考える・刈る", pat:["put"]},
  {t:"prec", m:"祈る・価値", pat:["preci","precat"]},
  {t:"pung", m:"刺す", pat:["pung","punct","poign"]},
  {t:"pug", m:"戦う", pat:["pugn"]},
  {t:"priv", m:"切り離す", pat:["priv"]},
  {t:"rid", m:"笑う", pat:["ridicul","derid","deris"]},
  {t:"sen", m:"老い", pat:["senil","senat","senior"]},
  {t:"sper", m:"希望", pat:["desper","prosper"]},
  {t:"asper", m:"粗い", pat:["asper"]},
  {t:"spond", m:"誓う・応える", pat:["spond","spons"]},
  {t:"stingu", m:"消す・突く", pat:["stingu","stinct"]},
  {t:"tail", m:"切る", pat:["tail"]},
  {t:"text", m:"織る", pat:["text"]},
  {t:"tut", m:"守る・教える", pat:["tutor","tuiti","tutel"]},
  {t:"jur", m:"法・誓う", pat:["jur","judic","justi"]},
  {t:"lat", m:"運ぶ(latum)", pat:["relat","translat","superlat","elat"]},
  {t:"limin", m:"敷居", pat:["limin"]},
  {t:"liter", m:"文字", pat:["liter"]},
  {t:"luct", m:"苦闘", pat:["luct"]},
  {t:"lun", m:"月", pat:["lunar","lunat"]},
  {t:"mar", m:"海", pat:["marine","marit"]},
  {t:"mater", m:"母", pat:["matern","matri"]},
  {t:"pater", m:"父", pat:["patern","patri","patron"]},
  {t:"merg", m:"沈む", pat:["merg","mers"]},
  {t:"min", m:"突き出る", pat:["eminen","promin","imminen","menac"]},
  {t:"minu", m:"小さい", pat:["minut","minish","minim","minor"]},
  {t:"mir", m:"驚く", pat:["mirac","admir","marvel"]},
  {t:"mod", m:"尺度", pat:["mod"]},
  {t:"mon", m:"警告・示す", pat:["monit","monish","monstr"]},
  {t:"mun", m:"義務・贈与", pat:["muni"]},
  {t:"nav", m:"船", pat:["navig","naval"]},
  {t:"nect", m:"結ぶ", pat:["nect","nex"]},
  {t:"noct", m:"夜", pat:["noct"]},
  {t:"not", m:"印・知る", pat:["notic","notif","notion","notor","denot","annot","notabl"]},
  {t:"numer", m:"数", pat:["numer"]},
  {t:"nutr", m:"養う", pat:["nutri","nurtu","nouris"]},
  {t:"ord", m:"順序", pat:["ordin","order"]},
  {t:"pac", m:"平和", pat:["pacif","appeas"]},
  {t:"par", m:"見える", pat:["appar","transpar"]},
  {t:"pari", m:"等しい", pat:["compar","dispar","parit"]},
  {t:"plor", m:"叫ぶ・泣く", pat:["plor"]},
  {t:"pred", m:"獲物", pat:["preda"]},
  {t:"dom", m:"家・支配", pat:["domin","domest","domic","domit"]},
  {t:"dorm", m:"眠る", pat:["dorm"]},
  {t:"dol", m:"悲しみ", pat:["condol","dolef","indolen"]},
  {t:"dub", m:"疑う", pat:["dubi"]},
  {t:"dyn", m:"力", pat:["dynam","dynast"]},
  {t:"fug", m:"逃げる", pat:["fug"]},
  {t:"fund", m:"底・注ぐ", pat:["fund","found"]},
  {t:"fract", m:"壊す", pat:["fract","frag","fring"]},
  {t:"fend", m:"打つ", pat:["fend","fens"]},
  {t:"flict", m:"打つ", pat:["flict"]},
  {t:"flor", m:"花", pat:["flor","flour"]},
  {t:"grav", m:"重い", pat:["grav","griev"]},
  {t:"hum", m:"土・低い", pat:["humili","humbl"]},
  {t:"insul", m:"島", pat:["insul","isolat"]},
  {t:"iter", m:"行く(ire)", pat:["transit","itiner","initi","ambiti"]},
  {t:"langu", m:"弱る", pat:["langui"]},
  {t:"maj", m:"より大きい", pat:["major","maxim","majest"]},
  {t:"ment", m:"心", pat:["mental","dement","mentio"]},
  {t:"omni", m:"すべて", pat:["omni"]},
  {t:"oper", m:"働く", pat:["oper"]},
  {t:"pand", m:"広げる", pat:["expand","expans"]},
  {t:"plaud", m:"拍手", pat:["plaud","plaus"]},
  {t:"propri", m:"自分の", pat:["propri"]},
  {t:"pud", m:"恥", pat:["repudi","impud"]},
  {t:"pur", m:"清い", pat:["purif","purit","impur"]},
  {t:"rig", m:"硬い", pat:["rigid","rigor"]},
  {t:"riv", m:"川", pat:["rival","deriv"]},
  {t:"rob", m:"力強い", pat:["robust","corrobor"]},
  {t:"rud", m:"粗い", pat:["rudim","erudit"]},
  {t:"salu", m:"健康", pat:["salut"]},
  {t:"sap", m:"味わう・知る", pat:["sapien","savor","insipid"]},
  {t:"semin", m:"種", pat:["semin"]},
  {t:"serv", m:"仕える・保つ", pat:["serv"]},
  {t:"soci", m:"仲間", pat:["soci"]},
  {t:"sol", m:"ひとり", pat:["solit","desolat","soliloqu","sullen"]},
  {t:"somn", m:"眠り", pat:["somn"]},
  {t:"stell", m:"星", pat:["stell"]},
  {t:"stig", m:"印・刺す", pat:["stigm","instig"]},
  {t:"suad", m:"勧める", pat:["suad","suas"]},
  {t:"sum", m:"取る", pat:["sume","sumpt"]},
  {t:"surg", m:"立ち上がる", pat:["surg","surrect"]},
  {t:"tac", m:"黙る", pat:["tacit","reticen"]},
  {t:"temper", m:"調節する", pat:["temper"]},
  {t:"tempt", m:"試す", pat:["tempt"]},
  {t:"temn", m:"軽蔑する", pat:["contempt","contemn"]},
  {t:"toler", m:"耐える", pat:["toler"]},
  {t:"torp", m:"鈍い", pat:["torp"]},
  {t:"trem", m:"震える", pat:["trem"]},
  {t:"trep", m:"おののく", pat:["trepid"]},
  {t:"trit", m:"すり減る", pat:["trite","attrit","contrit"]},
  {t:"ultim", m:"最後", pat:["ultim"]},
  {t:"veh", m:"運ぶ", pat:["vehic","vehem"]},
  {t:"vel", m:"覆う", pat:["veil","reveal","velop"]},
  {t:"verg", m:"傾く", pat:["verge","converg","diverg"]},
  {t:"vest", m:"衣・投資", pat:["vest"]},
  {t:"vig", m:"活気", pat:["vigor","vigil","invigor","surveil"]},
  {t:"vot", m:"誓う", pat:["devot","votio","vote"]},
  {t:"vuls", m:"引き抜く", pat:["vuls"]},
  {t:"ferv", m:"沸き立つ", pat:["ferv","ferment"]},
  {t:"fraud", m:"欺く", pat:["fraud"]},
  {t:"laud", m:"褒める", pat:["laud"]},
  {t:"audac", m:"大胆(audere)", pat:["audac"]},
  {t:"hered", m:"相続", pat:["hered","herit"]},
  {t:"dign", m:"値する・威厳", pat:["dign"]},
  {t:"crim", m:"罪", pat:["crim"]},
  {t:"juven", m:"若い", pat:["juven"]},
  {t:"melior", m:"より良い", pat:["melior"]},
  {t:"splend", m:"輝く", pat:["splend"]},
  {t:"linqu", m:"残す・離れる", pat:["linqu"]},
  {t:"flagr", m:"燃える", pat:["flagr"]},
  {t:"capit", m:"頭", pat:["capit","cipit"]},
  {t:"cresc", m:"育つ・増える", pat:["cresc","crement","accru"]},
  {t:"alter", m:"他の(alter)", pat:["alter","altru"]},
  {t:"am", m:"愛する(amare)", pat:["amicab","amiab","enamor","amorous","enmit"]},
  {t:"acer", m:"鋭い(acer)", pat:["acerb","acrid","acrim"]},
  {t:"apt", m:"適した(aptus)", pat:["adept","inept","aptit"]},
  {t:"agon", m:"闘い(ギリシャ)", pat:["agon"]},
  {t:"alt", m:"高い(altus)", pat:["exalt","altitud","haught"]},
  {t:"alesc", m:"育つ(alere)", pat:["alesc","adolesc"]},
  {t:"ard", m:"燃える(ardere)", pat:["ardor","arden","ardu"]},
  {t:"auster", m:"厳しい(ギリシャ)", pat:["auster"]},
  {t:"aug", m:"増やす(augere)", pat:["augment"]},
  {t:"brev", m:"短い(brevis)", pat:["brevi","abbrevi","abridg"]},
  {t:"cand", m:"白く輝く(candere)", pat:["candid","candor","incandes"]},
  {t:"capr", m:"山羊(caper)", pat:["capric"]},
  {t:"caust", m:"焼く(ギリシャ)", pat:["caust"]},
  {t:"cinct", m:"締める(cingere)", pat:["cinct"]},
  {t:"clem", m:"温和(clemens)", pat:["clemen"]},
  {t:"clim", m:"気候・傾き(ギリシャ)", pat:["climat","climax"]},
  {t:"coerc", m:"閉じ込める(arcere)", pat:["coerc"]},
  {t:"cup", m:"欲する(cupere)", pat:["covet","cupid"]},
  {t:"culp", m:"罪(culpa)", pat:["culp"]},
  {t:"crypt", m:"隠す(ギリシャ)", pat:["crypt"]},
  {t:"deb", m:"負う(debere)", pat:["debt","duly","dutif"]},
  {t:"dogm", m:"考え(ギリシャ)", pat:["dogm"]},
  {t:"ev", m:"時代(aevum)", pat:["longev","mediev","primev"]},
  {t:"fab", m:"話す(fari)", pat:["affab","fabl","ineffab"]},
  {t:"fabr", m:"職人(faber)", pat:["fabric"]},
  {t:"fall", m:"欺く(fallere)", pat:["fallac","fallib","falsif"]},
  {t:"febr", m:"熱(febris)", pat:["fever"]},
  {t:"flam", m:"炎(flamma)", pat:["flamb","flamm","inflam"]},
  {t:"grand", m:"大きい(grandis)", pat:["grand"]},
  {t:"hemer", m:"日(ギリシャ)", pat:["ephemer"]},
  {t:"hom", m:"人(homo)", pat:["homag","homici"]},
  {t:"imper", m:"命令・支配(imperare)", pat:["imperiou","imperat"]},
  {t:"ira", m:"怒り(ira)", pat:["irate","irasc"]},
  {t:"jubil", m:"歓呼(jubilare)", pat:["jubil"]},
  {t:"lament", m:"嘆く(lamentari)", pat:["lament"]},
  {t:"latu", m:"広い(latus)", pat:["latitud","dilat"]},
  {t:"leth", m:"忘却(ギリシャ)", pat:["letharg"]},
  {t:"litig", m:"訴訟(lis)", pat:["litig"]},
  {t:"macul", m:"染み(macula)", pat:["macul"]},
  {t:"mal", m:"悪(malus)", pat:["malign","malic"]},
  {t:"mont", m:"山・登る(mons)", pat:["mount"]},
  {t:"mor", m:"習慣(mos)", pat:["moral","moros"]},
  {t:"nebul", m:"霧(nebula)", pat:["nebul"]},
  {t:"nihil", m:"無(nihil/nullus)", pat:["nihil","null"]},
  {t:"omin", m:"前兆(omen)", pat:["ominou","abomin"]},
  {t:"op", m:"富・力(ops)", pat:["opulen","copiou"]},
  {t:"ops", m:"目(ギリシャ)", pat:["myop","synops"]},
  {t:"palp", m:"触れる(palpare)", pat:["palp"]},
  {t:"pauc", m:"少ない(paucus)", pat:["paucit"]},
  {t:"pecc", m:"罪を犯す(peccare)", pat:["pecc"]},
  {t:"peril", m:"危険(periculum)", pat:["peril"]},
  {t:"phren", m:"心(ギリシャ)", pat:["phren","frenz"]},
  {t:"plant", m:"植える(planta)", pat:["plant"]},
  {t:"pragma", m:"行う(ギリシャ)", pat:["pragma"]},
  {t:"prompt", m:"取り出す(promere)", pat:["prompt"]},
  {t:"prud", m:"先見(providere)", pat:["pruden"]},
  {t:"queri", m:"嘆く(queri)", pat:["querul","quarrel"]},
  {t:"quies", m:"静けさ(quies)", pat:["quiesc","tranquil"]},
  {t:"ranc", m:"腐る(rancere)", pat:["rancor","rancid"]},
  {t:"rap", m:"奪う(rapere)", pat:["rapac","surrept","rapid","ravag","ravish"]},
  {t:"sag", m:"鋭い・賢い(sagire)", pat:["sagac"]},
  {t:"scrup", m:"良心の呵責(scrupulus)", pat:["scrup"]},
  {t:"seren", m:"晴れた(serenus)", pat:["serene","serenit"]},
  {t:"solac", m:"慰める(solari)", pat:["solace","consolat"]},
  {t:"solid", m:"固い(solidus)", pat:["solid"]},
  {t:"stup", m:"呆然(stupere)", pat:["stupor","stupef","stupend"]},
  {t:"suprem", m:"最上(supremus)", pat:["suprem"]},
  {t:"ted", m:"飽きる(taedium)", pat:["tediu","tedio"]},
  {t:"temer", m:"無謀(temere)", pat:["temeri"]},
  {t:"trunc", m:"幹・切る(truncus)", pat:["trunc"]},
  {t:"tyran", m:"専制(ギリシャ)", pat:["tyran"]},
  {t:"ubiqu", m:"どこにでも(ubique)", pat:["ubiqu"]},
  {t:"vic", m:"交代・代理(vicis)", pat:["vicar","viciss"]},
  {t:"vil", m:"卑しい(vilis)", pat:["vilif","revil"]},
  {t:"vindic", m:"守る・報復(vindicare)", pat:["vindic","vendett","venge"]},
  {t:"vir", m:"男・力(vir)", pat:["viril","virtu"]},
  {t:"virul", m:"毒(virus)", pat:["virul"]},
  {t:"vola", m:"飛ぶ(volare)", pat:["volatil"]},
  {t:"zeal", m:"熱意(ギリシャzelos)", pat:["zeal"]},
];
const PREFIX_DEFS=[
  {t:"trans", m:"越えて"},
  {t:"inter", m:"間の"},
  {t:"circum", m:"周りに"},
  {t:"counter", m:"対抗して"},
  {t:"super", m:"上に"},
  {t:"under", m:"下に"},
  {t:"over", m:"越えて"},
  {t:"anti", m:"反対の"},
  {t:"auto", m:"自ら"},
  {t:"bene", m:"良い"},
  {t:"mal", m:"悪い"},
  {t:"micro", m:"小さい"},
  {t:"tele", m:"遠い"},
  {t:"mono", m:"単一の"},
  {t:"multi", m:"多数の"},
  {t:"semi", m:"半分の"},
  {t:"hyper", m:"過度に"},
  {t:"hypo", m:"下に・不足"},
  {t:"meta", m:"変化・超越"},
  {t:"para", m:"側に・逆らって"},
  {t:"peri", m:"周りに"},
  {t:"epi", m:"上に"},
  {t:"dia", m:"通して"},
  {t:"syn", m:"共に"},
  {t:"sym", m:"共に"},
  {t:"retro", m:"後ろへ"},
  {t:"extra", m:"外の"},
  {t:"intro", m:"中へ"},
  {t:"fore", m:"前の"},
  {t:"hetero", m:"異なる"},
  {t:"homo", m:"同じ"},
  {t:"neo", m:"新しい"},
  {t:"with", m:"逆らって"},
  {t:"con", m:"共に"},
  {t:"com", m:"共に"},
  {t:"sub", m:"下に"},
  {t:"pre", m:"前もって"},
  {t:"pro", m:"前へ"},
  {t:"per", m:"通して"},
  {t:"dis", m:"離れて・否定"},
  {t:"mis", m:"誤って"},
  {t:"out", m:"外へ・超えて"},
  {t:"un", m:"否定"},
  {t:"en", m:"中に・〜にする"},
  {t:"em", m:"中に・〜にする"},
  {t:"re", m:"再び・後ろへ"},
  {t:"de", m:"下へ・離れて"},
  {t:"ex", m:"外へ"},
  {t:"in", m:"中へ・否定"},
  {t:"ob", m:"逆らって"},
  {t:"ad", m:"〜の方へ"},
  {t:"ab", m:"離れて"},
  {t:"be", m:"すっかり・〜に(古英語)"},
  {t:"eu", m:"良い(ギリシャ)"},
  {t:"post", m:"後に"},
];
/* 誤タグの抑制: 単語 → 付けない語根名(レビューで確認した誤検出) */
const ROOT_BLOCK={
  "acrimony":["crim"],
  "aftermath":["term"],
  "alienate":["nat"],
  "allegiance":["lect"],
  "ameliorate":["ora"],
  "ammunition":["mun"],
  "annul":["ann"],
  "apoplectic":["lect"],
  "apparel":["par"],
  "apparition":["pari"],
  "ascertain":["tain"],
  "avalanche":["val"],
  "avid":["vis"],
  "bedlam":["pre:be"],
  "behemoth":["mob","pre:be"],
  "behest":["her"],
  "bemused":["sed"],
  "blockade":["loc"],
  "bludgeon":["geo"],
  "burgeon":["geo"],
  "calamity":["mit"],
  "caliber":["liber"],
  "castigate":["tact"],
  "catastrophe":["astr"],
  "cavalier":["val"],
  "chivalrous":["val"],
  "clamber":["clam"],
  "clammy":["clam"],
  "clinch":["clin"],
  "coffer":["fer"],
  "cogent":["gen"],
  "conflagration":["grat"],
  "consecrate":["crat"],
  "consternation":["nat"],
  "contaminate":["nat"],
  "contempt":["tempt"],
  "contingency":["gen"],
  "corroborate":["ora"],
  "culminate":["nat"],
  "culmination":["nat"],
  "curb":["urb"],
  "cynicism":["cid"],
  "deflect":["lect"],
  "denigrate":["grat"],
  "desecrate":["crat"],
  "detonate":["nat"],
  "devise":["via"],
  "diatribe":["trib"],
  "dilatory":["latu"],
  "disentangle":["sens","tact"],
  "dregs":["rect"],
  "effervescent":["fer"],
  "elaborate":["ora"],
  "elegy":["lect"],
  "emanate":["nat"],
  "embellish":["bell"],
  "encumbrance":["umbr"],
  "engrave":["grav"],
  "enmity":["mit"],
  "errand":["err"],
  "ethereal":["her"],
  "exigency":["gen"],
  "exorcise":["cid"],
  "extradite":["radi"],
  "extravagant":["rap"],
  "falter":["alter"],
  "ferment":["fer"],
  "ferocity":["fer"],
  "fervent":["ven","fer"],
  "fervor":["fer"],
  "feverishly":["veri"],
  "fickle":["fac"],
  "fidget":["fid"],
  "fluctuate":["luct"],
  "fluster":["flu"],
  "formidable":["form"],
  "forthright":["fort"],
  "fragrant":["fract"],
  "futile":["util"],
  "gamut":["mut"],
  "gaudy":["aud"],
  "gravitate":["viv"],
  "gridlock":["loc"],
  "havoc":["voc"],
  "henceforth":["fort"],
  "hereditary":["her"],
  "heresy":["her"],
  "hermit":["mit"],
  "hibernate":["nat"],
  "idiosyncratic":["crat"],
  "impersonate":["nat","son"],
  "impound":["pos"],
  "impoverished":["veri"],
  "improvise":["prob"],
  "incrementally":["ment"],
  "incriminate":["nat"],
  "indefatigable":["tact"],
  "indigent":["gen"],
  "indignation":["nat"],
  "indoctrinate":["nat"],
  "indulgent":["gen"],
  "inexorable":["nect"],
  "inferno":["fer"],
  "insolvent":["ven"],
  "insomnia":["omni"],
  "intermittently":["term"],
  "interrogate":["err"],
  "intransigence":["gen"],
  "invigorate":["ora"],
  "irascible":["sci"],
  "lavish":["vis"],
  "litigation":["tact"],
  "livestock":["vest"],
  "lucrative":["crat"],
  "machination":["nat"],
  "massacre":["sacr"],
  "maudlin":["aud"],
  "maverick":["veri"],
  "migraine":["migr"],
  "mitigate":["mit"],
  "monastery":["astr"],
  "moratorium":["ora"],
  "mundane":["und"],
  "mutilate":["util"],
  "obfuscate":["fus"],
  "obsequious":["equ"],
  "obstinate":["nat"],
  "oligarchy":["lig"],
  "opaque":["aqua"],
  "orchestrate":["her"],
  "ornate":["nat"],
  "oscillate":["sci"],
  "overbearing":["verb"],
  "overrule":["err"],
  "overrun":["err"],
  "overshadow":["vert"],
  "oversight":["vert"],
  "overstate":["vert"],
  "overthrow":["vert"],
  "overtly":["vert"],
  "overture":["vert"],
  "pandemonium":["dem"],
  "paragon":["agon"],
  "parch":["arch"],
  "pathetic":["thes"],
  "peddle":["ped"],
  "pejorative":["ora"],
  "pelt":["puls"],
  "pilfer":["fer"],
  "platitude":["latu"],
  "plaudit":["laud"],
  "postulate":["pre:post"],
  "posture":["pre:post"],
  "precipice":["prec"],
  "precipitate":["prec"],
  "precipitous":["prec"],
  "prerequisite":["equ"],
  "prestige":["tact"],
  "pristine":["prehend"],
  "procrastinate":["nat"],
  "provenance":["prob"],
  "provision":["prob"],
  "provocation":["prob"],
  "proximity":["mit"],
  "pulverize":["veri"],
  "quirk":["quir"],
  "reciprocate":["cap"],
  "refurbish":["urb"],
  "regale":["rect"],
  "regurgitate":["rect"],
  "rejuvenate":["nat"],
  "relinquish":["quir"],
  "reprimand":["prim","mand"],
  "requisition":["equ"],
  "rescind":["sci"],
  "resplendent":["plen"],
  "resuscitate":["sci"],
  "reverie":["veri"],
  "ruminate":["nat"],
  "sacred":["cred"],
  "scavenge":["vindic"],
  "scintillating":["sci"],
  "scurry":["cur"],
  "seclusion":["lud"],
  "seditious":["sed"],
  "sequester":["quir"],
  "shabby":["hab"],
  "sidestep":["sed"],
  "smother":["mob"],
  "snatch":["nat"],
  "spartan":["part"],
  "splendor":["plen"],
  "sporadic":["radi"],
  "squirm":["quir"],
  "stagnate":["nat"],
  "stampede":["ped"],
  "stupendous":["pend"],
  "sultry":["sal"],
  "summit":["mit"],
  "surveillance":["vel"],
  "taint":["tain"],
  "tribulation":["trib"],
  "trudge":["trud"],
  "underrate":["err"],
  "unkempt":["empt"],
  "upheaval":["val"],
  "uprising":["prehend"],
  "utensil":["tend"],
  "vacillate":["vac"],
  "vanquish":["quir"],
  "veneer":["ven"],
  "venerable":["ven"],
  "venerate":["ven"],
  "vestige":["vest"],
  "vicissitude":["cid"],
  "visceral":["vis"],
  "warden":["ard"],
};

/* パターンを長い順に展開(短い綴りの誤爆を減らす)。3文字パターンは2つ目のタグには使わない */
const _ROOT_PATS=(()=>{
  const a=[];
  ROOT_DEFS.forEach((r,i)=>r.pat.forEach(p=>a.push([p,i])));
  a.sort((x,y)=> y[0].length-x[0].length || 0);
  return a;
})();
const _PREFIX_ORDER=PREFIX_DEFS.map((p,i)=>i).sort((a,b)=>PREFIX_DEFS[b].t.length-PREFIX_DEFS[a].t.length);

const _rootsCache={};
/* 単語 → タグ列(最大2)。要素: {kind:"R"|"P", i:辞書index}。語根優先・接頭辞は1つまで */
function wordRoots(en){
  if(_rootsCache[en]) return _rootsCache[en];
  const w=en.toLowerCase();
  const blocked=ROOT_BLOCK[w]||[];
  const tags=[], got={};
  for(const [p,i] of _ROOT_PATS){
    if(got[i]) continue;
    if(blocked.indexOf(ROOT_DEFS[i].t)>=0) continue;
    if(p.length<4 && tags.length>=1) continue;
    if(w.indexOf(p)>=0){ tags.push({kind:"R", i}); got[i]=1; if(tags.length>=2) break; }
  }
  if(tags.length<2){
    for(const i of _PREFIX_ORDER){
      const p=PREFIX_DEFS[i].t;
      if(w.startsWith(p) && w.length-p.length>=4 && blocked.indexOf("pre:"+p)<0){
        tags.push({kind:"P", i}); break;
      }
    }
  }
  return _rootsCache[en]=tags;
}
/* 共鳴判定に使う語根IDのみ(接頭辞は家族が大きすぎるため対象外) */
function rootIdsOf(en){
  return wordRoots(en).filter(t=>t.kind==="R").map(t=>t.i);
}
/* 表示用テキスト: "spec(見る)・pre-(前もって)" */
function rootText(en){
  const tags=wordRoots(en);
  if(!tags.length) return "";
  return tags.map(t=> t.kind==="R"
    ? ROOT_DEFS[t.i].t+"("+ROOT_DEFS[t.i].m+")"
    : PREFIX_DEFS[t.i].t+"-("+PREFIX_DEFS[t.i].m+")").join("・");
}
